// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: client.proto
// Protobuf C++ Version: 6.33.4

#include "client.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Next {

inline constexpr TeamBattleNPC::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        actor_id_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR TeamBattleNPC::TeamBattleNPC(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TeamBattleNPC_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TeamBattleNPCDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TeamBattleNPCDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TeamBattleNPCDefaultTypeInternal() {}
  union {
    TeamBattleNPC _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TeamBattleNPCDefaultTypeInternal _TeamBattleNPC_default_instance_;

inline constexpr LastEquipBall::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        equipballid_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR LastEquipBall::LastEquipBall(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(LastEquipBall_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LastEquipBallDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LastEquipBallDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LastEquipBallDefaultTypeInternal() {}
  union {
    LastEquipBall _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LastEquipBallDefaultTypeInternal _LastEquipBall_default_instance_;

inline constexpr HasP2Win::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        haswin_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR HasP2Win::HasP2Win(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(HasP2Win_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct HasP2WinDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HasP2WinDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HasP2WinDefaultTypeInternal() {}
  union {
    HasP2Win _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HasP2WinDefaultTypeInternal _HasP2Win_default_instance_;

inline constexpr FBEyeOpen::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        isopen_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR FBEyeOpen::FBEyeOpen(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(FBEyeOpen_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FBEyeOpenDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FBEyeOpenDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FBEyeOpenDefaultTypeInternal() {}
  union {
    FBEyeOpen _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FBEyeOpenDefaultTypeInternal _FBEyeOpen_default_instance_;

inline constexpr PointList::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        points_{} {}

template <typename>
PROTOBUF_CONSTEXPR PointList::PointList(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PointList_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PointListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PointListDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PointListDefaultTypeInternal() {}
  union {
    PointList _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PointListDefaultTypeInternal _PointList_default_instance_;
}  // namespace Next
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_client_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_client_2eproto = nullptr;
const ::uint32_t
    TableStruct_client_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Next::PointList, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Next::PointList, _impl_.points_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Next::TeamBattleNPC, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Next::TeamBattleNPC, _impl_.actor_id_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Next::FBEyeOpen, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Next::FBEyeOpen, _impl_.isopen_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Next::HasP2Win, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Next::HasP2Win, _impl_.haswin_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Next::LastEquipBall, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Next::LastEquipBall, _impl_.equipballid_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Next::PointList)},
        {5, sizeof(::Next::TeamBattleNPC)},
        {10, sizeof(::Next::FBEyeOpen)},
        {15, sizeof(::Next::HasP2Win)},
        {20, sizeof(::Next::LastEquipBall)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::Next::_PointList_default_instance_._instance,
    &::Next::_TeamBattleNPC_default_instance_._instance,
    &::Next::_FBEyeOpen_default_instance_._instance,
    &::Next::_HasP2Win_default_instance_._instance,
    &::Next::_LastEquipBall_default_instance_._instance,
};
const char descriptor_table_protodef_client_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014client.proto\022\004Next\032\024com_base_types.pro"
    "to\032\016xls_enum.proto\"(\n\tPointList\022\033\n\006point"
    "s\030\001 \003(\0132\013.Next.Point\"!\n\rTeamBattleNPC\022\020\n"
    "\010actor_id\030\001 \001(\003\"\033\n\tFBEyeOpen\022\016\n\006IsOpen\030\001"
    " \001(\003\"\032\n\010HasP2Win\022\016\n\006HasWin\030\001 \001(\003\"$\n\rLast"
    "EquipBall\022\023\n\013EquipBallId\030\001 \001(\003"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_client_2eproto_deps[2] = {
        &::descriptor_table_com_5fbase_5ftypes_2eproto,
        &::descriptor_table_xls_5fenum_2eproto,
};
static ::absl::once_flag descriptor_table_client_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_client_2eproto = {
    false,
    false,
    230,
    descriptor_table_protodef_client_2eproto,
    "client.proto",
    &descriptor_table_client_2eproto_once,
    descriptor_table_client_2eproto_deps,
    2,
    5,
    schemas,
    file_default_instances,
    TableStruct_client_2eproto::offsets,
    file_level_enum_descriptors_client_2eproto,
    file_level_service_descriptors_client_2eproto,
};
namespace Next {
// ===================================================================

class PointList::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PointList>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PointList, _impl_._has_bits_);
};

void PointList::clear_points() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.points_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
PointList::PointList(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PointList_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Next.PointList)
}
PROTOBUF_NDEBUG_INLINE PointList::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Next::PointList& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        points_{visibility, arena, from.points_} {}

PointList::PointList(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PointList& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PointList_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PointList* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:Next.PointList)
}
PROTOBUF_NDEBUG_INLINE PointList::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        points_{visibility, arena} {}

inline void PointList::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PointList::~PointList() {
  // @@protoc_insertion_point(destructor:Next.PointList)
  SharedDtor(*this);
}
inline void PointList::SharedDtor(MessageLite& self) {
  PointList& this_ = static_cast<PointList&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PointList::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PointList(arena);
}
constexpr auto PointList::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(PointList, _impl_.points_) +
          decltype(PointList::_impl_.points_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(PointList), alignof(PointList), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&PointList::PlacementNew_,
                                 sizeof(PointList),
                                 alignof(PointList));
  }
}
constexpr auto PointList::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PointList_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PointList::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PointList>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PointList::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PointList>(), &PointList::ByteSizeLong,
              &PointList::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PointList, _impl_._cached_size_),
          false,
      },
      &PointList::kDescriptorMethods,
      &descriptor_table_client_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PointList_class_data_ =
        PointList::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PointList::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PointList_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PointList_class_data_.tc_table);
  return PointList_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
PointList::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PointList, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    PointList_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Next::PointList>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .Next.Point points = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(PointList, _impl_.points_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .Next.Point points = 1;
    {PROTOBUF_FIELD_OFFSET(PointList, _impl_.points_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::Next::Point>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void PointList::Clear() {
// @@protoc_insertion_point(message_clear_start:Next.PointList)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.points_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PointList::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PointList& this_ = static_cast<const PointList&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PointList::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PointList& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Next.PointList)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .Next.Point points = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_points_size());
         i < n; i++) {
      const auto& repfield = this_._internal_points().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Next.PointList)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PointList::ByteSizeLong(const MessageLite& base) {
  const PointList& this_ = static_cast<const PointList&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PointList::ByteSizeLong() const {
  const PointList& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Next.PointList)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .Next.Point points = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_points_size();
      for (const auto& msg : this_._internal_points()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PointList::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PointList*>(&to_msg);
  auto& from = static_cast<const PointList&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Next.PointList)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_points()->InternalMergeFromWithArena(
        ::google::protobuf::MessageLite::internal_visibility(), arena,
        from._internal_points());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PointList::CopyFrom(const PointList& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Next.PointList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PointList::InternalSwap(PointList* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.points_.InternalSwap(&other->_impl_.points_);
}

::google::protobuf::Metadata PointList::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TeamBattleNPC::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<TeamBattleNPC>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TeamBattleNPC, _impl_._has_bits_);
};

TeamBattleNPC::TeamBattleNPC(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TeamBattleNPC_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Next.TeamBattleNPC)
}
TeamBattleNPC::TeamBattleNPC(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TeamBattleNPC& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TeamBattleNPC_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE TeamBattleNPC::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void TeamBattleNPC::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.actor_id_ = {};
}
TeamBattleNPC::~TeamBattleNPC() {
  // @@protoc_insertion_point(destructor:Next.TeamBattleNPC)
  SharedDtor(*this);
}
inline void TeamBattleNPC::SharedDtor(MessageLite& self) {
  TeamBattleNPC& this_ = static_cast<TeamBattleNPC&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TeamBattleNPC::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TeamBattleNPC(arena);
}
constexpr auto TeamBattleNPC::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(TeamBattleNPC),
                                            alignof(TeamBattleNPC));
}
constexpr auto TeamBattleNPC::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TeamBattleNPC_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &TeamBattleNPC::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TeamBattleNPC>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TeamBattleNPC::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TeamBattleNPC>(), &TeamBattleNPC::ByteSizeLong,
              &TeamBattleNPC::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TeamBattleNPC, _impl_._cached_size_),
          false,
      },
      &TeamBattleNPC::kDescriptorMethods,
      &descriptor_table_client_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TeamBattleNPC_class_data_ =
        TeamBattleNPC::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TeamBattleNPC::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TeamBattleNPC_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TeamBattleNPC_class_data_.tc_table);
  return TeamBattleNPC_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
TeamBattleNPC::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TeamBattleNPC, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    TeamBattleNPC_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Next::TeamBattleNPC>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int64 actor_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TeamBattleNPC, _impl_.actor_id_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(TeamBattleNPC, _impl_.actor_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int64 actor_id = 1;
    {PROTOBUF_FIELD_OFFSET(TeamBattleNPC, _impl_.actor_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void TeamBattleNPC::Clear() {
// @@protoc_insertion_point(message_clear_start:Next.TeamBattleNPC)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.actor_id_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TeamBattleNPC::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TeamBattleNPC& this_ = static_cast<const TeamBattleNPC&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TeamBattleNPC::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TeamBattleNPC& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Next.TeamBattleNPC)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int64 actor_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
            stream, this_._internal_actor_id(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Next.TeamBattleNPC)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TeamBattleNPC::ByteSizeLong(const MessageLite& base) {
  const TeamBattleNPC& this_ = static_cast<const TeamBattleNPC&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TeamBattleNPC::ByteSizeLong() const {
  const TeamBattleNPC& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Next.TeamBattleNPC)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // optional int64 actor_id = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_actor_id());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TeamBattleNPC::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<TeamBattleNPC*>(&to_msg);
  auto& from = static_cast<const TeamBattleNPC&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Next.TeamBattleNPC)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_impl_.actor_id_ = from._impl_.actor_id_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void TeamBattleNPC::CopyFrom(const TeamBattleNPC& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Next.TeamBattleNPC)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TeamBattleNPC::InternalSwap(TeamBattleNPC* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.actor_id_, other->_impl_.actor_id_);
}

::google::protobuf::Metadata TeamBattleNPC::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class FBEyeOpen::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<FBEyeOpen>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(FBEyeOpen, _impl_._has_bits_);
};

FBEyeOpen::FBEyeOpen(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FBEyeOpen_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Next.FBEyeOpen)
}
FBEyeOpen::FBEyeOpen(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FBEyeOpen& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FBEyeOpen_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE FBEyeOpen::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void FBEyeOpen::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.isopen_ = {};
}
FBEyeOpen::~FBEyeOpen() {
  // @@protoc_insertion_point(destructor:Next.FBEyeOpen)
  SharedDtor(*this);
}
inline void FBEyeOpen::SharedDtor(MessageLite& self) {
  FBEyeOpen& this_ = static_cast<FBEyeOpen&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL FBEyeOpen::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) FBEyeOpen(arena);
}
constexpr auto FBEyeOpen::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(FBEyeOpen),
                                            alignof(FBEyeOpen));
}
constexpr auto FBEyeOpen::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_FBEyeOpen_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &FBEyeOpen::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<FBEyeOpen>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &FBEyeOpen::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<FBEyeOpen>(), &FBEyeOpen::ByteSizeLong,
              &FBEyeOpen::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(FBEyeOpen, _impl_._cached_size_),
          false,
      },
      &FBEyeOpen::kDescriptorMethods,
      &descriptor_table_client_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull FBEyeOpen_class_data_ =
        FBEyeOpen::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FBEyeOpen::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&FBEyeOpen_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(FBEyeOpen_class_data_.tc_table);
  return FBEyeOpen_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
FBEyeOpen::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(FBEyeOpen, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    FBEyeOpen_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Next::FBEyeOpen>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int64 IsOpen = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FBEyeOpen, _impl_.isopen_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(FBEyeOpen, _impl_.isopen_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int64 IsOpen = 1;
    {PROTOBUF_FIELD_OFFSET(FBEyeOpen, _impl_.isopen_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void FBEyeOpen::Clear() {
// @@protoc_insertion_point(message_clear_start:Next.FBEyeOpen)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.isopen_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL FBEyeOpen::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const FBEyeOpen& this_ = static_cast<const FBEyeOpen&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL FBEyeOpen::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const FBEyeOpen& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Next.FBEyeOpen)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int64 IsOpen = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
            stream, this_._internal_isopen(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Next.FBEyeOpen)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t FBEyeOpen::ByteSizeLong(const MessageLite& base) {
  const FBEyeOpen& this_ = static_cast<const FBEyeOpen&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t FBEyeOpen::ByteSizeLong() const {
  const FBEyeOpen& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Next.FBEyeOpen)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // optional int64 IsOpen = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_isopen());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void FBEyeOpen::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<FBEyeOpen*>(&to_msg);
  auto& from = static_cast<const FBEyeOpen&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Next.FBEyeOpen)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_impl_.isopen_ = from._impl_.isopen_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void FBEyeOpen::CopyFrom(const FBEyeOpen& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Next.FBEyeOpen)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FBEyeOpen::InternalSwap(FBEyeOpen* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.isopen_, other->_impl_.isopen_);
}

::google::protobuf::Metadata FBEyeOpen::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class HasP2Win::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<HasP2Win>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(HasP2Win, _impl_._has_bits_);
};

HasP2Win::HasP2Win(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HasP2Win_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Next.HasP2Win)
}
HasP2Win::HasP2Win(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const HasP2Win& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HasP2Win_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE HasP2Win::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void HasP2Win::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.haswin_ = {};
}
HasP2Win::~HasP2Win() {
  // @@protoc_insertion_point(destructor:Next.HasP2Win)
  SharedDtor(*this);
}
inline void HasP2Win::SharedDtor(MessageLite& self) {
  HasP2Win& this_ = static_cast<HasP2Win&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL HasP2Win::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) HasP2Win(arena);
}
constexpr auto HasP2Win::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(HasP2Win),
                                            alignof(HasP2Win));
}
constexpr auto HasP2Win::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_HasP2Win_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &HasP2Win::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<HasP2Win>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &HasP2Win::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<HasP2Win>(), &HasP2Win::ByteSizeLong,
              &HasP2Win::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(HasP2Win, _impl_._cached_size_),
          false,
      },
      &HasP2Win::kDescriptorMethods,
      &descriptor_table_client_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull HasP2Win_class_data_ =
        HasP2Win::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
HasP2Win::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&HasP2Win_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(HasP2Win_class_data_.tc_table);
  return HasP2Win_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
HasP2Win::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(HasP2Win, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    HasP2Win_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Next::HasP2Win>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int64 HasWin = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(HasP2Win, _impl_.haswin_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(HasP2Win, _impl_.haswin_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int64 HasWin = 1;
    {PROTOBUF_FIELD_OFFSET(HasP2Win, _impl_.haswin_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void HasP2Win::Clear() {
// @@protoc_insertion_point(message_clear_start:Next.HasP2Win)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.haswin_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL HasP2Win::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const HasP2Win& this_ = static_cast<const HasP2Win&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL HasP2Win::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const HasP2Win& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Next.HasP2Win)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int64 HasWin = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
            stream, this_._internal_haswin(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Next.HasP2Win)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t HasP2Win::ByteSizeLong(const MessageLite& base) {
  const HasP2Win& this_ = static_cast<const HasP2Win&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t HasP2Win::ByteSizeLong() const {
  const HasP2Win& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Next.HasP2Win)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // optional int64 HasWin = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_haswin());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void HasP2Win::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<HasP2Win*>(&to_msg);
  auto& from = static_cast<const HasP2Win&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Next.HasP2Win)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_impl_.haswin_ = from._impl_.haswin_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void HasP2Win::CopyFrom(const HasP2Win& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Next.HasP2Win)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void HasP2Win::InternalSwap(HasP2Win* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.haswin_, other->_impl_.haswin_);
}

::google::protobuf::Metadata HasP2Win::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class LastEquipBall::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<LastEquipBall>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(LastEquipBall, _impl_._has_bits_);
};

LastEquipBall::LastEquipBall(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, LastEquipBall_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Next.LastEquipBall)
}
LastEquipBall::LastEquipBall(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const LastEquipBall& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, LastEquipBall_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE LastEquipBall::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void LastEquipBall::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.equipballid_ = {};
}
LastEquipBall::~LastEquipBall() {
  // @@protoc_insertion_point(destructor:Next.LastEquipBall)
  SharedDtor(*this);
}
inline void LastEquipBall::SharedDtor(MessageLite& self) {
  LastEquipBall& this_ = static_cast<LastEquipBall&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL LastEquipBall::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) LastEquipBall(arena);
}
constexpr auto LastEquipBall::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(LastEquipBall),
                                            alignof(LastEquipBall));
}
constexpr auto LastEquipBall::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_LastEquipBall_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &LastEquipBall::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<LastEquipBall>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &LastEquipBall::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<LastEquipBall>(), &LastEquipBall::ByteSizeLong,
              &LastEquipBall::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(LastEquipBall, _impl_._cached_size_),
          false,
      },
      &LastEquipBall::kDescriptorMethods,
      &descriptor_table_client_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull LastEquipBall_class_data_ =
        LastEquipBall::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
LastEquipBall::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&LastEquipBall_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(LastEquipBall_class_data_.tc_table);
  return LastEquipBall_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
LastEquipBall::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(LastEquipBall, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    LastEquipBall_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Next::LastEquipBall>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int64 EquipBallId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(LastEquipBall, _impl_.equipballid_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(LastEquipBall, _impl_.equipballid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int64 EquipBallId = 1;
    {PROTOBUF_FIELD_OFFSET(LastEquipBall, _impl_.equipballid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void LastEquipBall::Clear() {
// @@protoc_insertion_point(message_clear_start:Next.LastEquipBall)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.equipballid_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL LastEquipBall::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const LastEquipBall& this_ = static_cast<const LastEquipBall&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL LastEquipBall::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const LastEquipBall& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Next.LastEquipBall)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int64 EquipBallId = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
            stream, this_._internal_equipballid(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Next.LastEquipBall)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t LastEquipBall::ByteSizeLong(const MessageLite& base) {
  const LastEquipBall& this_ = static_cast<const LastEquipBall&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t LastEquipBall::ByteSizeLong() const {
  const LastEquipBall& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Next.LastEquipBall)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // optional int64 EquipBallId = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_equipballid());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void LastEquipBall::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<LastEquipBall*>(&to_msg);
  auto& from = static_cast<const LastEquipBall&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Next.LastEquipBall)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_impl_.equipballid_ = from._impl_.equipballid_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void LastEquipBall::CopyFrom(const LastEquipBall& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Next.LastEquipBall)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LastEquipBall::InternalSwap(LastEquipBall* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.equipballid_, other->_impl_.equipballid_);
}

::google::protobuf::Metadata LastEquipBall::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Next
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_client_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
