// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: client.proto
// Protobuf C++ Version: 6.33.6

#ifndef client_2eproto_2epb_2eh
#define client_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033006
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "com_base_types.pb.h"
#include "xls_enum.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_client_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_client_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_client_2eproto;
}  // extern "C"
namespace Next {
class FBEyeOpen;
struct FBEyeOpenDefaultTypeInternal;
extern FBEyeOpenDefaultTypeInternal _FBEyeOpen_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FBEyeOpen_class_data_;
class HasP2Win;
struct HasP2WinDefaultTypeInternal;
extern HasP2WinDefaultTypeInternal _HasP2Win_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull HasP2Win_class_data_;
class LastEquipBall;
struct LastEquipBallDefaultTypeInternal;
extern LastEquipBallDefaultTypeInternal _LastEquipBall_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull LastEquipBall_class_data_;
class PointList;
struct PointListDefaultTypeInternal;
extern PointListDefaultTypeInternal _PointList_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PointList_class_data_;
class TeamBattleNPC;
struct TeamBattleNPCDefaultTypeInternal;
extern TeamBattleNPCDefaultTypeInternal _TeamBattleNPC_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TeamBattleNPC_class_data_;
}  // namespace Next
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Next {

// ===================================================================


// -------------------------------------------------------------------

class TeamBattleNPC final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Next.TeamBattleNPC) */ {
 public:
  inline TeamBattleNPC() : TeamBattleNPC(nullptr) {}
  ~TeamBattleNPC() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TeamBattleNPC* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TeamBattleNPC));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TeamBattleNPC(::google::protobuf::internal::ConstantInitialized);

  inline TeamBattleNPC(const TeamBattleNPC& from) : TeamBattleNPC(nullptr, from) {}
  inline TeamBattleNPC(TeamBattleNPC&& from) noexcept
      : TeamBattleNPC(nullptr, ::std::move(from)) {}
  inline TeamBattleNPC& operator=(const TeamBattleNPC& from) {
    CopyFrom(from);
    return *this;
  }
  inline TeamBattleNPC& operator=(TeamBattleNPC&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TeamBattleNPC& default_instance() {
    return *reinterpret_cast<const TeamBattleNPC*>(
        &_TeamBattleNPC_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(TeamBattleNPC& a, TeamBattleNPC& b) { a.Swap(&b); }
  inline void Swap(TeamBattleNPC* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TeamBattleNPC* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TeamBattleNPC* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TeamBattleNPC>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TeamBattleNPC& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TeamBattleNPC& from) { TeamBattleNPC::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TeamBattleNPC* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Next.TeamBattleNPC"; }

  explicit TeamBattleNPC(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TeamBattleNPC(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TeamBattleNPC& from);
  TeamBattleNPC(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TeamBattleNPC&& from) noexcept
      : TeamBattleNPC(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kActorIdFieldNumber = 1,
  };
  // optional int64 actor_id = 1;
  bool has_actor_id() const;
  void clear_actor_id() ;
  ::int64_t actor_id() const;
  void set_actor_id(::int64_t value);

  private:
  ::int64_t _internal_actor_id() const;
  void _internal_set_actor_id(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:Next.TeamBattleNPC)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TeamBattleNPC& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t actor_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TeamBattleNPC_class_data_;
// -------------------------------------------------------------------

class LastEquipBall final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Next.LastEquipBall) */ {
 public:
  inline LastEquipBall() : LastEquipBall(nullptr) {}
  ~LastEquipBall() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LastEquipBall* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LastEquipBall));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LastEquipBall(::google::protobuf::internal::ConstantInitialized);

  inline LastEquipBall(const LastEquipBall& from) : LastEquipBall(nullptr, from) {}
  inline LastEquipBall(LastEquipBall&& from) noexcept
      : LastEquipBall(nullptr, ::std::move(from)) {}
  inline LastEquipBall& operator=(const LastEquipBall& from) {
    CopyFrom(from);
    return *this;
  }
  inline LastEquipBall& operator=(LastEquipBall&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LastEquipBall& default_instance() {
    return *reinterpret_cast<const LastEquipBall*>(
        &_LastEquipBall_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(LastEquipBall& a, LastEquipBall& b) { a.Swap(&b); }
  inline void Swap(LastEquipBall* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LastEquipBall* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LastEquipBall* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LastEquipBall>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LastEquipBall& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LastEquipBall& from) { LastEquipBall::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LastEquipBall* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Next.LastEquipBall"; }

  explicit LastEquipBall(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  LastEquipBall(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const LastEquipBall& from);
  LastEquipBall(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, LastEquipBall&& from) noexcept
      : LastEquipBall(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEquipBallIdFieldNumber = 1,
  };
  // optional int64 EquipBallId = 1;
  bool has_equipballid() const;
  void clear_equipballid() ;
  ::int64_t equipballid() const;
  void set_equipballid(::int64_t value);

  private:
  ::int64_t _internal_equipballid() const;
  void _internal_set_equipballid(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:Next.LastEquipBall)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const LastEquipBall& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t equipballid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull LastEquipBall_class_data_;
// -------------------------------------------------------------------

class HasP2Win final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Next.HasP2Win) */ {
 public:
  inline HasP2Win() : HasP2Win(nullptr) {}
  ~HasP2Win() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HasP2Win* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HasP2Win));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HasP2Win(::google::protobuf::internal::ConstantInitialized);

  inline HasP2Win(const HasP2Win& from) : HasP2Win(nullptr, from) {}
  inline HasP2Win(HasP2Win&& from) noexcept
      : HasP2Win(nullptr, ::std::move(from)) {}
  inline HasP2Win& operator=(const HasP2Win& from) {
    CopyFrom(from);
    return *this;
  }
  inline HasP2Win& operator=(HasP2Win&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HasP2Win& default_instance() {
    return *reinterpret_cast<const HasP2Win*>(
        &_HasP2Win_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(HasP2Win& a, HasP2Win& b) { a.Swap(&b); }
  inline void Swap(HasP2Win* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HasP2Win* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HasP2Win* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HasP2Win>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HasP2Win& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HasP2Win& from) { HasP2Win::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HasP2Win* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Next.HasP2Win"; }

  explicit HasP2Win(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  HasP2Win(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const HasP2Win& from);
  HasP2Win(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, HasP2Win&& from) noexcept
      : HasP2Win(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHasWinFieldNumber = 1,
  };
  // optional int64 HasWin = 1;
  bool has_haswin() const;
  void clear_haswin() ;
  ::int64_t haswin() const;
  void set_haswin(::int64_t value);

  private:
  ::int64_t _internal_haswin() const;
  void _internal_set_haswin(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:Next.HasP2Win)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const HasP2Win& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t haswin_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull HasP2Win_class_data_;
// -------------------------------------------------------------------

class FBEyeOpen final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Next.FBEyeOpen) */ {
 public:
  inline FBEyeOpen() : FBEyeOpen(nullptr) {}
  ~FBEyeOpen() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FBEyeOpen* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FBEyeOpen));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FBEyeOpen(::google::protobuf::internal::ConstantInitialized);

  inline FBEyeOpen(const FBEyeOpen& from) : FBEyeOpen(nullptr, from) {}
  inline FBEyeOpen(FBEyeOpen&& from) noexcept
      : FBEyeOpen(nullptr, ::std::move(from)) {}
  inline FBEyeOpen& operator=(const FBEyeOpen& from) {
    CopyFrom(from);
    return *this;
  }
  inline FBEyeOpen& operator=(FBEyeOpen&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FBEyeOpen& default_instance() {
    return *reinterpret_cast<const FBEyeOpen*>(
        &_FBEyeOpen_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(FBEyeOpen& a, FBEyeOpen& b) { a.Swap(&b); }
  inline void Swap(FBEyeOpen* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FBEyeOpen* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FBEyeOpen* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FBEyeOpen>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FBEyeOpen& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FBEyeOpen& from) { FBEyeOpen::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FBEyeOpen* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Next.FBEyeOpen"; }

  explicit FBEyeOpen(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FBEyeOpen(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FBEyeOpen& from);
  FBEyeOpen(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FBEyeOpen&& from) noexcept
      : FBEyeOpen(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIsOpenFieldNumber = 1,
  };
  // optional int64 IsOpen = 1;
  bool has_isopen() const;
  void clear_isopen() ;
  ::int64_t isopen() const;
  void set_isopen(::int64_t value);

  private:
  ::int64_t _internal_isopen() const;
  void _internal_set_isopen(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:Next.FBEyeOpen)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FBEyeOpen& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t isopen_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull FBEyeOpen_class_data_;
// -------------------------------------------------------------------

class PointList final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Next.PointList) */ {
 public:
  inline PointList() : PointList(nullptr) {}
  ~PointList() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PointList* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PointList));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PointList(::google::protobuf::internal::ConstantInitialized);

  inline PointList(const PointList& from) : PointList(nullptr, from) {}
  inline PointList(PointList&& from) noexcept
      : PointList(nullptr, ::std::move(from)) {}
  inline PointList& operator=(const PointList& from) {
    CopyFrom(from);
    return *this;
  }
  inline PointList& operator=(PointList&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PointList& default_instance() {
    return *reinterpret_cast<const PointList*>(
        &_PointList_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PointList& a, PointList& b) { a.Swap(&b); }
  inline void Swap(PointList* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PointList* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PointList* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PointList>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PointList& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PointList& from) { PointList::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PointList* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Next.PointList"; }

  explicit PointList(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PointList(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PointList& from);
  PointList(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PointList&& from) noexcept
      : PointList(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPointsFieldNumber = 1,
  };
  // repeated .Next.Point points = 1;
  int points_size() const;
  private:
  int _internal_points_size() const;

  public:
  void clear_points() ;
  ::Next::Point* PROTOBUF_NONNULL mutable_points(int index);
  ::google::protobuf::RepeatedPtrField<::Next::Point>* PROTOBUF_NONNULL mutable_points();

  private:
  const ::google::protobuf::RepeatedPtrField<::Next::Point>& _internal_points() const;
  ::google::protobuf::RepeatedPtrField<::Next::Point>* PROTOBUF_NONNULL _internal_mutable_points();
  public:
  const ::Next::Point& points(int index) const;
  ::Next::Point* PROTOBUF_NONNULL add_points();
  const ::google::protobuf::RepeatedPtrField<::Next::Point>& points() const;
  // @@protoc_insertion_point(class_scope:Next.PointList)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PointList& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::Next::Point > points_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PointList_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PointList

// repeated .Next.Point points = 1;
inline int PointList::_internal_points_size() const {
  return _internal_points().size();
}
inline int PointList::points_size() const {
  return _internal_points_size();
}
inline ::Next::Point* PROTOBUF_NONNULL PointList::mutable_points(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Next.PointList.points)
  return _internal_mutable_points()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Next::Point>* PROTOBUF_NONNULL PointList::mutable_points()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:Next.PointList.points)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_points();
}
inline const ::Next::Point& PointList::points(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Next.PointList.points)
  return _internal_points().Get(index);
}
inline ::Next::Point* PROTOBUF_NONNULL PointList::add_points()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Next::Point* _add =
      _internal_mutable_points()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:Next.PointList.points)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Next::Point>& PointList::points() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Next.PointList.points)
  return _internal_points();
}
inline const ::google::protobuf::RepeatedPtrField<::Next::Point>&
PointList::_internal_points() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.points_;
}
inline ::google::protobuf::RepeatedPtrField<::Next::Point>* PROTOBUF_NONNULL
PointList::_internal_mutable_points() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.points_;
}

// -------------------------------------------------------------------

// TeamBattleNPC

// optional int64 actor_id = 1;
inline bool TeamBattleNPC::has_actor_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void TeamBattleNPC::clear_actor_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.actor_id_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int64_t TeamBattleNPC::actor_id() const {
  // @@protoc_insertion_point(field_get:Next.TeamBattleNPC.actor_id)
  return _internal_actor_id();
}
inline void TeamBattleNPC::set_actor_id(::int64_t value) {
  _internal_set_actor_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:Next.TeamBattleNPC.actor_id)
}
inline ::int64_t TeamBattleNPC::_internal_actor_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.actor_id_;
}
inline void TeamBattleNPC::_internal_set_actor_id(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.actor_id_ = value;
}

// -------------------------------------------------------------------

// FBEyeOpen

// optional int64 IsOpen = 1;
inline bool FBEyeOpen::has_isopen() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void FBEyeOpen::clear_isopen() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isopen_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int64_t FBEyeOpen::isopen() const {
  // @@protoc_insertion_point(field_get:Next.FBEyeOpen.IsOpen)
  return _internal_isopen();
}
inline void FBEyeOpen::set_isopen(::int64_t value) {
  _internal_set_isopen(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:Next.FBEyeOpen.IsOpen)
}
inline ::int64_t FBEyeOpen::_internal_isopen() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.isopen_;
}
inline void FBEyeOpen::_internal_set_isopen(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isopen_ = value;
}

// -------------------------------------------------------------------

// HasP2Win

// optional int64 HasWin = 1;
inline bool HasP2Win::has_haswin() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void HasP2Win::clear_haswin() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.haswin_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int64_t HasP2Win::haswin() const {
  // @@protoc_insertion_point(field_get:Next.HasP2Win.HasWin)
  return _internal_haswin();
}
inline void HasP2Win::set_haswin(::int64_t value) {
  _internal_set_haswin(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:Next.HasP2Win.HasWin)
}
inline ::int64_t HasP2Win::_internal_haswin() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.haswin_;
}
inline void HasP2Win::_internal_set_haswin(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.haswin_ = value;
}

// -------------------------------------------------------------------

// LastEquipBall

// optional int64 EquipBallId = 1;
inline bool LastEquipBall::has_equipballid() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void LastEquipBall::clear_equipballid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.equipballid_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int64_t LastEquipBall::equipballid() const {
  // @@protoc_insertion_point(field_get:Next.LastEquipBall.EquipBallId)
  return _internal_equipballid();
}
inline void LastEquipBall::set_equipballid(::int64_t value) {
  _internal_set_equipballid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:Next.LastEquipBall.EquipBallId)
}
inline ::int64_t LastEquipBall::_internal_equipballid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.equipballid_;
}
inline void LastEquipBall::_internal_set_equipballid(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.equipballid_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Next


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // client_2eproto_2epb_2eh
