// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com_friend_data.proto
// Protobuf C++ Version: 7.35.0

#include "com_friend_data.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::Next::FriendInteractEvent
        {&::_pbi::kDescriptorMethods, &::descriptor_table_com_5ffriend_5fdata_2eproto, /* tracker*/ nullptr,},
        // ::Next::FriendInteractRecord
        {&::_pbi::kDescriptorMethods, &::descriptor_table_com_5ffriend_5fdata_2eproto, /* tracker*/ nullptr,},
        // ::Next::FriendInteractRecordList
        {&::_pbi::kDescriptorMethods, &::descriptor_table_com_5ffriend_5fdata_2eproto, /* tracker*/ nullptr,},
        // ::Next::FriendRecommendInfo
        {&::_pbi::kDescriptorMethods, &::descriptor_table_com_5ffriend_5fdata_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace Next {
class FriendInteractRecord::_Internal {
 public:
  using HasBits = decltype(::std::declval<FriendInteractRecord>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(FriendInteractRecord, _impl_._has_bits_);
};

constexpr FriendInteractRecord::ParseTableT_ FriendInteractRecord::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(FriendInteractRecord, _impl_._has_bits_),
      0, // no _extensions_
      3, 24,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967288,  // skipmap
      offsetof(ParseTableT_, field_entries),
      3,  // num_field_entries
      1,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::Next::FriendInteractRecord>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // optional uint32 recommend_uin = 1 [json_name = "recommendUin"];
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FriendInteractRecord, _impl_.recommend_uin_), 0>(),
       {8, 0, 0,
        PROTOBUF_FIELD_OFFSET(FriendInteractRecord, _impl_.recommend_uin_)}},
      // optional .Next.FriendInteractEventType ev_type = 2 [json_name = "evType"];
      {::_pbi::TcParser::FastEr0S1,
       {16, 1, 10,
        PROTOBUF_FIELD_OFFSET(FriendInteractRecord, _impl_.ev_type_)}},
      // optional uint32 ev_time = 3 [json_name = "evTime"];
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FriendInteractRecord, _impl_.ev_time_), 2>(),
       {24, 2, 0,
        PROTOBUF_FIELD_OFFSET(FriendInteractRecord, _impl_.ev_time_)}},
    }}, {{
      65535, 65535
    }}, {{
      // optional uint32 recommend_uin = 1 [json_name = "recommendUin"];
      {PROTOBUF_FIELD_OFFSET(FriendInteractRecord, _impl_.recommend_uin_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // optional .Next.FriendInteractEventType ev_type = 2 [json_name = "evType"];
      {PROTOBUF_FIELD_OFFSET(FriendInteractRecord, _impl_.ev_type_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
      // optional uint32 ev_time = 3 [json_name = "evTime"];
      {PROTOBUF_FIELD_OFFSET(FriendInteractRecord, _impl_.ev_time_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    }},
    {{
        {0, 10},
    }},
    {{
    }},
  };
}


inline constexpr FriendInteractRecord::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        recommend_uin_{0u},
        ev_type_{static_cast< ::Next::FriendInteractEventType >(0)},
        ev_time_{0u} {}

template <typename>
constexpr FriendInteractRecord::FriendInteractRecord(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL FriendInteractRecord::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) FriendInteractRecord(arena);
}
constexpr auto FriendInteractRecord::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(FriendInteractRecord), alignof(FriendInteractRecord));
}
constexpr auto FriendInteractRecord::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &FriendInteractRecord::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<FriendInteractRecord>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &FriendInteractRecord::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<FriendInteractRecord>(), &FriendInteractRecord::ByteSizeLong,
              &FriendInteractRecord::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(FriendInteractRecord, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_com_5ffriend_5fdata_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct FriendInteractRecordGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr FriendInteractRecordGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 FriendInteractRecord_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(FriendInteractRecord::InternalGenerateClassData_(
            _default, &FriendInteractRecord_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<FriendInteractRecord>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~FriendInteractRecordGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) FriendInteractRecord _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<FriendInteractRecord>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(FriendInteractRecordGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST FriendInteractRecordGlobalsTypeInternal FriendInteractRecord_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* FriendInteractRecord_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return FriendInteractRecord_globals_.GetClassData();
#else
  return FriendInteractRecord_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class FriendInteractEvent::_Internal {
 public:
  using HasBits = decltype(::std::declval<FriendInteractEvent>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(FriendInteractEvent, _impl_._has_bits_);
};

constexpr FriendInteractEvent::ParseTableT_ FriendInteractEvent::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(FriendInteractEvent, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      1,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::Next::FriendInteractEvent>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // optional .Next.FriendInteractEventType ev_type = 2 [json_name = "evType"];
      {::_pbi::TcParser::FastEr0S1,
       {16, 1, 10,
        PROTOBUF_FIELD_OFFSET(FriendInteractEvent, _impl_.ev_type_)}},
      // optional uint32 recommend_uin = 1 [json_name = "recommendUin"];
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FriendInteractEvent, _impl_.recommend_uin_), 0>(),
       {8, 0, 0,
        PROTOBUF_FIELD_OFFSET(FriendInteractEvent, _impl_.recommend_uin_)}},
    }}, {{
      65535, 65535
    }}, {{
      // optional uint32 recommend_uin = 1 [json_name = "recommendUin"];
      {PROTOBUF_FIELD_OFFSET(FriendInteractEvent, _impl_.recommend_uin_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // optional .Next.FriendInteractEventType ev_type = 2 [json_name = "evType"];
      {PROTOBUF_FIELD_OFFSET(FriendInteractEvent, _impl_.ev_type_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    }},
    {{
        {0, 10},
    }},
    {{
    }},
  };
}


inline constexpr FriendInteractEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        recommend_uin_{0u},
        ev_type_{static_cast< ::Next::FriendInteractEventType >(0)} {}

template <typename>
constexpr FriendInteractEvent::FriendInteractEvent(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL FriendInteractEvent::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) FriendInteractEvent(arena);
}
constexpr auto FriendInteractEvent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(FriendInteractEvent), alignof(FriendInteractEvent));
}
constexpr auto FriendInteractEvent::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &FriendInteractEvent::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<FriendInteractEvent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &FriendInteractEvent::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<FriendInteractEvent>(), &FriendInteractEvent::ByteSizeLong,
              &FriendInteractEvent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(FriendInteractEvent, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_com_5ffriend_5fdata_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct FriendInteractEventGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr FriendInteractEventGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 FriendInteractEvent_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(FriendInteractEvent::InternalGenerateClassData_(
            _default, &FriendInteractEvent_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<FriendInteractEvent>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~FriendInteractEventGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) FriendInteractEvent _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<FriendInteractEvent>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(FriendInteractEventGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST FriendInteractEventGlobalsTypeInternal FriendInteractEvent_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* FriendInteractEvent_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return FriendInteractEvent_globals_.GetClassData();
#else
  return FriendInteractEvent_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class FriendInteractRecordList::_Internal {
 public:
  using HasBits = decltype(::std::declval<FriendInteractRecordList>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(FriendInteractRecordList, _impl_._has_bits_);
};

constexpr FriendInteractRecordList::ParseTableT_ FriendInteractRecordList::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(FriendInteractRecordList, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      2,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::Next::FriendInteractRecordList>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // repeated .Next.FriendInteractRecord records = 2 [json_name = "records"];
      {::_pbi::TcParser::FastMtR1,
       {18, 0, 0,
        PROTOBUF_FIELD_OFFSET(FriendInteractRecordList, _impl_.records_)}},
      // optional .Next.FriendSource source = 1 [json_name = "source"];
      {::_pbi::TcParser::FastEr0S1,
       {8, 1, 8,
        PROTOBUF_FIELD_OFFSET(FriendInteractRecordList, _impl_.source_)}},
    }}, {{
      65535, 65535
    }}, {{
      // optional .Next.FriendSource source = 1 [json_name = "source"];
      {PROTOBUF_FIELD_OFFSET(FriendInteractRecordList, _impl_.source_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
      // repeated .Next.FriendInteractRecord records = 2 [json_name = "records"];
      {PROTOBUF_FIELD_OFFSET(FriendInteractRecordList, _impl_.records_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::Next::FriendInteractRecord>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::Next::FriendInteractRecord_globals_},
        #endif
        {0, 8},
    }},
    {{
    }},
  };
}


inline constexpr FriendInteractRecordList::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        records_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::Next::FriendInteractRecordList,
            PROTOBUF_FIELD_OFFSET(::Next::FriendInteractRecordList, _impl_.records_)>()
         }
        ,
        source_{static_cast< ::Next::FriendSource >(0)} {}

template <typename>
constexpr FriendInteractRecordList::FriendInteractRecordList(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL FriendInteractRecordList::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) FriendInteractRecordList(arena);
}
constexpr auto FriendInteractRecordList::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(FriendInteractRecordList), alignof(FriendInteractRecordList));
}
constexpr auto FriendInteractRecordList::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &FriendInteractRecordList::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<FriendInteractRecordList>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &FriendInteractRecordList::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<FriendInteractRecordList>(), &FriendInteractRecordList::ByteSizeLong,
              &FriendInteractRecordList::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(FriendInteractRecordList, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[2],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_com_5ffriend_5fdata_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct FriendInteractRecordListGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr FriendInteractRecordListGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 FriendInteractRecordList_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(FriendInteractRecordList::InternalGenerateClassData_(
            _default, &FriendInteractRecordList_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<FriendInteractRecordList>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~FriendInteractRecordListGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) FriendInteractRecordList _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<FriendInteractRecordList>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(FriendInteractRecordListGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST FriendInteractRecordListGlobalsTypeInternal FriendInteractRecordList_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* FriendInteractRecordList_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return FriendInteractRecordList_globals_.GetClassData();
#else
  return FriendInteractRecordList_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class FriendRecommendInfo::_Internal {
 public:
  using HasBits = decltype(::std::declval<FriendRecommendInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(FriendRecommendInfo, _impl_._has_bits_);
};

constexpr FriendRecommendInfo::ParseTableT_ FriendRecommendInfo::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(FriendRecommendInfo, _impl_._has_bits_),
      0, // no _extensions_
      1, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967294,  // skipmap
      offsetof(ParseTableT_, field_entries),
      1,  // num_field_entries
      1,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::Next::FriendRecommendInfo>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // repeated .Next.FriendInteractRecordList record_lists = 1 [json_name = "recordLists"];
      {::_pbi::TcParser::FastMtR1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(FriendRecommendInfo, _impl_.record_lists_)}},
    }}, {{
      65535, 65535
    }}, {{
      // repeated .Next.FriendInteractRecordList record_lists = 1 [json_name = "recordLists"];
      {PROTOBUF_FIELD_OFFSET(FriendRecommendInfo, _impl_.record_lists_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::Next::FriendInteractRecordList>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::Next::FriendInteractRecordList_globals_},
        #endif
    }},
    {{
    }},
  };
}


inline constexpr FriendRecommendInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        record_lists_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::Next::FriendRecommendInfo,
            PROTOBUF_FIELD_OFFSET(::Next::FriendRecommendInfo, _impl_.record_lists_)>()
         }
     {}

template <typename>
constexpr FriendRecommendInfo::FriendRecommendInfo(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL FriendRecommendInfo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) FriendRecommendInfo(arena);
}
constexpr auto FriendRecommendInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(FriendRecommendInfo), alignof(FriendRecommendInfo));
}
constexpr auto FriendRecommendInfo::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &FriendRecommendInfo::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<FriendRecommendInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &FriendRecommendInfo::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<FriendRecommendInfo>(), &FriendRecommendInfo::ByteSizeLong,
              &FriendRecommendInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(FriendRecommendInfo, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[3],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_com_5ffriend_5fdata_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct FriendRecommendInfoGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr FriendRecommendInfoGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 FriendRecommendInfo_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(FriendRecommendInfo::InternalGenerateClassData_(
            _default, &FriendRecommendInfo_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<FriendRecommendInfo>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~FriendRecommendInfoGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) FriendRecommendInfo _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<FriendRecommendInfo>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(FriendRecommendInfoGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST FriendRecommendInfoGlobalsTypeInternal FriendRecommendInfo_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* FriendRecommendInfo_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return FriendRecommendInfo_globals_.GetClassData();
#else
  return FriendRecommendInfo_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace Next
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_com_5ffriend_5fdata_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_com_5ffriend_5fdata_2eproto = nullptr;
const ::uint32_t
    TableStruct_com_5ffriend_5fdata_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Next::FriendInteractEvent, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Next::FriendInteractEvent, _impl_.recommend_uin_),
        PROTOBUF_FIELD_OFFSET(::Next::FriendInteractEvent, _impl_.ev_type_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Next::FriendInteractRecord, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Next::FriendInteractRecord, _impl_.recommend_uin_),
        PROTOBUF_FIELD_OFFSET(::Next::FriendInteractRecord, _impl_.ev_type_),
        PROTOBUF_FIELD_OFFSET(::Next::FriendInteractRecord, _impl_.ev_time_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Next::FriendInteractRecordList, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Next::FriendInteractRecordList, _impl_.source_),
        PROTOBUF_FIELD_OFFSET(::Next::FriendInteractRecordList, _impl_.records_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Next::FriendRecommendInfo, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Next::FriendRecommendInfo, _impl_.record_lists_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Next::FriendInteractEvent)},
        {7, sizeof(::Next::FriendInteractRecord)},
        {16, sizeof(::Next::FriendInteractRecordList)},
        {23, sizeof(::Next::FriendRecommendInfo)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::Next::FriendInteractEvent_globals_,
        &::Next::FriendInteractRecord_globals_,
        &::Next::FriendInteractRecordList_globals_,
        &::Next::FriendRecommendInfo_globals_,
};
const char descriptor_table_protodef_com_5ffriend_5fdata_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025com_friend_data.proto\022\004Next\"r\n\023FriendI"
    "nteractEvent\022#\n\rrecommend_uin\030\001 \001(\rR\014rec"
    "ommendUin\0226\n\007ev_type\030\002 \001(\0162\035.Next.Friend"
    "InteractEventTypeR\006evType\"\214\001\n\024FriendInte"
    "ractRecord\022#\n\rrecommend_uin\030\001 \001(\rR\014recom"
    "mendUin\0226\n\007ev_type\030\002 \001(\0162\035.Next.FriendIn"
    "teractEventTypeR\006evType\022\027\n\007ev_time\030\003 \001(\r"
    "R\006evTime\"|\n\030FriendInteractRecordList\022*\n\006"
    "source\030\001 \001(\0162\022.Next.FriendSourceR\006source"
    "\0224\n\007records\030\002 \003(\0132\032.Next.FriendInteractR"
    "ecordR\007records\"X\n\023FriendRecommendInfo\022A\n"
    "\014record_lists\030\001 \003(\0132\036.Next.FriendInterac"
    "tRecordListR\013recordLists*\202\004\n\027FriendInter"
    "actEventType\022#\n\037FRIEND_INTERACT_EVENT_TY"
    "PE_NONE\020\000\022$\n FRIEND_INTERACT_EVENT_TYPE_"
    "VISIT\020\001\022.\n*FRIEND_INTERACT_EVENT_TYPE_RI"
    "ST_HOLD_HANDS\020\002\022.\n*FRIEND_INTERACT_EVENT"
    "_TYPE_INVITE_TOGETHER\020\003\022,\n(FRIEND_INTERA"
    "CT_EVENT_TYPE_FRIEND_BATTLE\020\004\0221\n-FRIEND_"
    "INTERACT_EVENT_TYPE_WORLD_LEADER_FIGHT\020\005"
    "\022/\n+FRIEND_INTERACT_EVENT_TYPE_LENENDARY"
    "_BATTLE\020\006\022+\n\'FRIEND_INTERACT_EVENT_TYPE_"
    "BLOOD_BATTLE\020\007\022\"\n\036FRIEND_INTERACT_EVENT_"
    "TYPE_PVP\020\010\022)\n%FRIEND_INTERACT_EVENT_TYPE"
    "_VISIT_HOME\020\t\022.\n*FRIEND_INTERACT_EVENT_T"
    "YPE_TOY_INTERACTION\020\n*\274\001\n\014FriendSource\022\026"
    "\n\022FRIEND_SOURCE_NONE\020\000\022\014\n\010FS_VISIT\020\001\022\n\n\006"
    "FS_PVP\020\002\022\027\n\023FS_PET_EGG_EXCHANGE\020\003\022\021\n\rFS_"
    "PVP_COMBAT\020\004\022\017\n\013FS_TOGETHER\020\005\022\022\n\016FS_TEAM"
    "_COMBAT\020\006\022\026\n\022FS_TOY_INTERACTION\020\007\022\021\n\rFS_"
    "VISIT_HOME\020\010"
};
static ::absl::once_flag descriptor_table_com_5ffriend_5fdata_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_com_5ffriend_5fdata_2eproto = {
    false,
    false,
    1212,
    descriptor_table_protodef_com_5ffriend_5fdata_2eproto,
    "com_friend_data.proto",
    &descriptor_table_com_5ffriend_5fdata_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_message_globals,
    TableStruct_com_5ffriend_5fdata_2eproto::offsets,
    file_level_enum_descriptors_com_5ffriend_5fdata_2eproto,
    file_level_service_descriptors_com_5ffriend_5fdata_2eproto,
};
namespace Next {
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
FriendInteractEventType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_com_5ffriend_5fdata_2eproto);
  return file_level_enum_descriptors_com_5ffriend_5fdata_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t FriendInteractEventType_internal_data_[] = {
    720896u, 0u, };
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
FriendSource_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_com_5ffriend_5fdata_2eproto);
  return file_level_enum_descriptors_com_5ffriend_5fdata_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t FriendSource_internal_data_[] = {
    589824u, 0u, };
// ===================================================================

FriendInteractEvent::FriendInteractEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FriendInteractEvent_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Next.FriendInteractEvent)
}
FriendInteractEvent::FriendInteractEvent(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FriendInteractEvent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FriendInteractEvent_get_class_data()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE FriendInteractEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void FriendInteractEvent::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, recommend_uin_),
           0,
           offsetof(Impl_, ev_type_) -
               offsetof(Impl_, recommend_uin_) +
               sizeof(Impl_::ev_type_));
}
FriendInteractEvent::~FriendInteractEvent() {
  // @@protoc_insertion_point(destructor:Next.FriendInteractEvent)
  SharedDtor(*this);
}
inline void FriendInteractEvent::SharedDtor(MessageLite& self) {
  FriendInteractEvent& this_ = static_cast<FriendInteractEvent&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull FriendInteractEvent_class_data_ =
        FriendInteractEvent::InternalGenerateClassData_(FriendInteractEvent_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FriendInteractEvent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&FriendInteractEvent_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(FriendInteractEvent_class_data_.tc_table);
  return FriendInteractEvent_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FriendInteractEvent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&FriendInteractEvent_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&FriendInteractEvent_globals_));
  return FriendInteractEvent_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const FriendInteractEvent::ParseTableT_
    FriendInteractEvent::_table_ =
        FriendInteractEvent::InternalGenerateParseTable_(FriendInteractEvent_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void FriendInteractEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:Next.FriendInteractEvent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    ::memset(&_impl_.recommend_uin_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.ev_type_) -
        reinterpret_cast<char*>(&_impl_.recommend_uin_)) + sizeof(_impl_.ev_type_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL FriendInteractEvent::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const FriendInteractEvent& this_ = static_cast<const FriendInteractEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL FriendInteractEvent::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const FriendInteractEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Next.FriendInteractEvent)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 recommend_uin = 1 [json_name = "recommendUin"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_recommend_uin(), target);
  }

  // optional .Next.FriendInteractEventType ev_type = 2 [json_name = "evType"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this_._internal_ev_type(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Next.FriendInteractEvent)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t FriendInteractEvent::ByteSizeLong(const MessageLite& base) {
  const FriendInteractEvent& this_ = static_cast<const FriendInteractEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t FriendInteractEvent::ByteSizeLong() const {
  const FriendInteractEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Next.FriendInteractEvent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // optional uint32 recommend_uin = 1 [json_name = "recommendUin"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_recommend_uin());
    }
    // optional .Next.FriendInteractEventType ev_type = 2 [json_name = "evType"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_ev_type());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void FriendInteractEvent::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<FriendInteractEvent*>(&to_msg);
  auto& from = static_cast<const FriendInteractEvent&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Next.FriendInteractEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.recommend_uin_ = from._impl_.recommend_uin_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.ev_type_ = from._impl_.ev_type_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void FriendInteractEvent::CopyFrom(const FriendInteractEvent& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Next.FriendInteractEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FriendInteractEvent::InternalSwap(FriendInteractEvent* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FriendInteractEvent, _impl_.ev_type_)
      + sizeof(FriendInteractEvent::_impl_.ev_type_)
      - PROTOBUF_FIELD_OFFSET(FriendInteractEvent, _impl_.recommend_uin_)>(
          reinterpret_cast<char*>(&_impl_.recommend_uin_),
          reinterpret_cast<char*>(&other->_impl_.recommend_uin_));
}

::google::protobuf::Metadata FriendInteractEvent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

FriendInteractRecord::FriendInteractRecord(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FriendInteractRecord_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Next.FriendInteractRecord)
}
FriendInteractRecord::FriendInteractRecord(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FriendInteractRecord& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FriendInteractRecord_get_class_data()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE FriendInteractRecord::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void FriendInteractRecord::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, recommend_uin_),
           0,
           offsetof(Impl_, ev_time_) -
               offsetof(Impl_, recommend_uin_) +
               sizeof(Impl_::ev_time_));
}
FriendInteractRecord::~FriendInteractRecord() {
  // @@protoc_insertion_point(destructor:Next.FriendInteractRecord)
  SharedDtor(*this);
}
inline void FriendInteractRecord::SharedDtor(MessageLite& self) {
  FriendInteractRecord& this_ = static_cast<FriendInteractRecord&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull FriendInteractRecord_class_data_ =
        FriendInteractRecord::InternalGenerateClassData_(FriendInteractRecord_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FriendInteractRecord::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&FriendInteractRecord_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(FriendInteractRecord_class_data_.tc_table);
  return FriendInteractRecord_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FriendInteractRecord::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&FriendInteractRecord_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&FriendInteractRecord_globals_));
  return FriendInteractRecord_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const FriendInteractRecord::ParseTableT_
    FriendInteractRecord::_table_ =
        FriendInteractRecord::InternalGenerateParseTable_(FriendInteractRecord_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void FriendInteractRecord::Clear() {
// @@protoc_insertion_point(message_clear_start:Next.FriendInteractRecord)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    ::memset(&_impl_.recommend_uin_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.ev_time_) -
        reinterpret_cast<char*>(&_impl_.recommend_uin_)) + sizeof(_impl_.ev_time_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL FriendInteractRecord::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const FriendInteractRecord& this_ = static_cast<const FriendInteractRecord&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL FriendInteractRecord::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const FriendInteractRecord& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Next.FriendInteractRecord)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 recommend_uin = 1 [json_name = "recommendUin"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_recommend_uin(), target);
  }

  // optional .Next.FriendInteractEventType ev_type = 2 [json_name = "evType"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this_._internal_ev_type(), target);
  }

  // optional uint32 ev_time = 3 [json_name = "evTime"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this_._internal_ev_time(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Next.FriendInteractRecord)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t FriendInteractRecord::ByteSizeLong(const MessageLite& base) {
  const FriendInteractRecord& this_ = static_cast<const FriendInteractRecord&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t FriendInteractRecord::ByteSizeLong() const {
  const FriendInteractRecord& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Next.FriendInteractRecord)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // optional uint32 recommend_uin = 1 [json_name = "recommendUin"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_recommend_uin());
    }
    // optional .Next.FriendInteractEventType ev_type = 2 [json_name = "evType"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_ev_type());
    }
    // optional uint32 ev_time = 3 [json_name = "evTime"];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_ev_time());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void FriendInteractRecord::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<FriendInteractRecord*>(&to_msg);
  auto& from = static_cast<const FriendInteractRecord&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Next.FriendInteractRecord)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.recommend_uin_ = from._impl_.recommend_uin_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.ev_type_ = from._impl_.ev_type_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.ev_time_ = from._impl_.ev_time_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void FriendInteractRecord::CopyFrom(const FriendInteractRecord& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Next.FriendInteractRecord)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FriendInteractRecord::InternalSwap(FriendInteractRecord* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FriendInteractRecord, _impl_.ev_time_)
      + sizeof(FriendInteractRecord::_impl_.ev_time_)
      - PROTOBUF_FIELD_OFFSET(FriendInteractRecord, _impl_.recommend_uin_)>(
          reinterpret_cast<char*>(&_impl_.recommend_uin_),
          reinterpret_cast<char*>(&other->_impl_.recommend_uin_));
}

::google::protobuf::Metadata FriendInteractRecord::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

FriendInteractRecordList::FriendInteractRecordList(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FriendInteractRecordList_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Next.FriendInteractRecordList)
}
PROTOBUF_NDEBUG_INLINE FriendInteractRecordList::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Next::FriendInteractRecordList& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        records_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::Next::FriendInteractRecordList,
              PROTOBUF_FIELD_OFFSET(::Next::FriendInteractRecordList, _impl_.records_)>()
          , from.records_
        }
     {}

FriendInteractRecordList::FriendInteractRecordList(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const FriendInteractRecordList& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FriendInteractRecordList_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FriendInteractRecordList* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.source_ = from._impl_.source_;

  // @@protoc_insertion_point(copy_constructor:Next.FriendInteractRecordList)
}
PROTOBUF_NDEBUG_INLINE FriendInteractRecordList::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        records_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::Next::FriendInteractRecordList,
            PROTOBUF_FIELD_OFFSET(::Next::FriendInteractRecordList, _impl_.records_)>()
         }
     {}

inline void FriendInteractRecordList::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.source_ = {};
}
FriendInteractRecordList::~FriendInteractRecordList() {
  // @@protoc_insertion_point(destructor:Next.FriendInteractRecordList)
  SharedDtor(*this);
}
inline void FriendInteractRecordList::SharedDtor(MessageLite& self) {
  FriendInteractRecordList& this_ = static_cast<FriendInteractRecordList&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull FriendInteractRecordList_class_data_ =
        FriendInteractRecordList::InternalGenerateClassData_(FriendInteractRecordList_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FriendInteractRecordList::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&FriendInteractRecordList_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(FriendInteractRecordList_class_data_.tc_table);
  return FriendInteractRecordList_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FriendInteractRecordList::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&FriendInteractRecordList_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&FriendInteractRecordList_globals_));
  return FriendInteractRecordList_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const FriendInteractRecordList::ParseTableT_
    FriendInteractRecordList::_table_ =
        FriendInteractRecordList::InternalGenerateParseTable_(FriendInteractRecordList_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void FriendInteractRecordList::Clear() {
// @@protoc_insertion_point(message_clear_start:Next.FriendInteractRecordList)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.records_.Clear();
  }
  _impl_.source_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL FriendInteractRecordList::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const FriendInteractRecordList& this_ = static_cast<const FriendInteractRecordList&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL FriendInteractRecordList::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const FriendInteractRecordList& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Next.FriendInteractRecordList)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional .Next.FriendSource source = 1 [json_name = "source"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this_._internal_source(), target);
  }

  // repeated .Next.FriendInteractRecord records = 2 [json_name = "records"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_records_size());
         i < n; i++) {
      const auto& repfield = this_._internal_records().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              2, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Next.FriendInteractRecordList)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t FriendInteractRecordList::ByteSizeLong(const MessageLite& base) {
  const FriendInteractRecordList& this_ = static_cast<const FriendInteractRecordList&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t FriendInteractRecordList::ByteSizeLong() const {
  const FriendInteractRecordList& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Next.FriendInteractRecordList)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated .Next.FriendInteractRecord records = 2 [json_name = "records"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_records_size();
      for (const auto& msg : this_._internal_records()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // optional .Next.FriendSource source = 1 [json_name = "source"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_source());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void FriendInteractRecordList::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<FriendInteractRecordList*>(&to_msg);
  auto& from = static_cast<const FriendInteractRecordList&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Next.FriendInteractRecordList)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_records()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_records());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.source_ = from._impl_.source_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void FriendInteractRecordList::CopyFrom(const FriendInteractRecordList& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Next.FriendInteractRecordList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FriendInteractRecordList::InternalSwap(FriendInteractRecordList* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.records_.InternalSwap(&other->_impl_.records_);
  swap(_impl_.source_, other->_impl_.source_);
}

::google::protobuf::Metadata FriendInteractRecordList::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

FriendRecommendInfo::FriendRecommendInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FriendRecommendInfo_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Next.FriendRecommendInfo)
}
PROTOBUF_NDEBUG_INLINE FriendRecommendInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Next::FriendRecommendInfo& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        record_lists_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::Next::FriendRecommendInfo,
              PROTOBUF_FIELD_OFFSET(::Next::FriendRecommendInfo, _impl_.record_lists_)>()
          , from.record_lists_
        }
     {}

FriendRecommendInfo::FriendRecommendInfo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const FriendRecommendInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FriendRecommendInfo_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FriendRecommendInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:Next.FriendRecommendInfo)
}
PROTOBUF_NDEBUG_INLINE FriendRecommendInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        record_lists_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::Next::FriendRecommendInfo,
            PROTOBUF_FIELD_OFFSET(::Next::FriendRecommendInfo, _impl_.record_lists_)>()
         }
     {}

inline void FriendRecommendInfo::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
FriendRecommendInfo::~FriendRecommendInfo() {
  // @@protoc_insertion_point(destructor:Next.FriendRecommendInfo)
  SharedDtor(*this);
}
inline void FriendRecommendInfo::SharedDtor(MessageLite& self) {
  FriendRecommendInfo& this_ = static_cast<FriendRecommendInfo&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull FriendRecommendInfo_class_data_ =
        FriendRecommendInfo::InternalGenerateClassData_(FriendRecommendInfo_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FriendRecommendInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&FriendRecommendInfo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(FriendRecommendInfo_class_data_.tc_table);
  return FriendRecommendInfo_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FriendRecommendInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&FriendRecommendInfo_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&FriendRecommendInfo_globals_));
  return FriendRecommendInfo_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const FriendRecommendInfo::ParseTableT_
    FriendRecommendInfo::_table_ =
        FriendRecommendInfo::InternalGenerateParseTable_(FriendRecommendInfo_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void FriendRecommendInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:Next.FriendRecommendInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.record_lists_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL FriendRecommendInfo::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const FriendRecommendInfo& this_ = static_cast<const FriendRecommendInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL FriendRecommendInfo::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const FriendRecommendInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Next.FriendRecommendInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .Next.FriendInteractRecordList record_lists = 1 [json_name = "recordLists"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_record_lists_size());
         i < n; i++) {
      const auto& repfield = this_._internal_record_lists().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Next.FriendRecommendInfo)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t FriendRecommendInfo::ByteSizeLong(const MessageLite& base) {
  const FriendRecommendInfo& this_ = static_cast<const FriendRecommendInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t FriendRecommendInfo::ByteSizeLong() const {
  const FriendRecommendInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Next.FriendRecommendInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .Next.FriendInteractRecordList record_lists = 1 [json_name = "recordLists"];
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_record_lists_size();
      for (const auto& msg : this_._internal_record_lists()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void FriendRecommendInfo::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<FriendRecommendInfo*>(&to_msg);
  auto& from = static_cast<const FriendRecommendInfo&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Next.FriendRecommendInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_record_lists()->InternalMergeFromWithArena(
        ::google::protobuf::MessageLite::internal_visibility(), arena,
        from._internal_record_lists());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void FriendRecommendInfo::CopyFrom(const FriendRecommendInfo& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Next.FriendRecommendInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FriendRecommendInfo::InternalSwap(FriendRecommendInfo* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.record_lists_.InternalSwap(&other->_impl_.record_lists_);
}

::google::protobuf::Metadata FriendRecommendInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Next
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_com_5ffriend_5fdata_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
