// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com_season.proto
// Protobuf C++ Version: 6.33.6

#include "com_season.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Next {

inline constexpr SeasonPetInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        is_nightmare_{false},
        is_shiny_{false},
        is_fantastic_{false},
        mix_blood_{0},
        refresh_batch_id_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR SeasonPetInfo::SeasonPetInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SeasonPetInfo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SeasonPetInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SeasonPetInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SeasonPetInfoDefaultTypeInternal() {}
  union {
    SeasonPetInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SeasonPetInfoDefaultTypeInternal _SeasonPetInfo_default_instance_;

inline constexpr BoxMonsterInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        box_type_{static_cast< ::Next::BoxType >(0)},
        is_shiny_{false},
        is_fantastic_{false},
        is_nightmare_{false},
        box_conf_id_{0u},
        pet_content_id_{0},
        belong_season_{0},
        monster_id_{0u},
        pet_rarity_type_{static_cast< ::Next::PetRarityType >(0)},
        pet_mutation_type_{static_cast< ::Next::PetMutationType >(0)},
        pet_nature_{0},
        gender_{0u},
        height_{0},
        weight_{0},
        refresh_batch_id_{::uint64_t{0u}},
        voice_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BoxMonsterInfo::BoxMonsterInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BoxMonsterInfo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BoxMonsterInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BoxMonsterInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BoxMonsterInfoDefaultTypeInternal() {}
  union {
    BoxMonsterInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BoxMonsterInfoDefaultTypeInternal _BoxMonsterInfo_default_instance_;

inline constexpr SeasonBattleInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        box_info_{nullptr},
        season_pet_info_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR SeasonBattleInfo::SeasonBattleInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SeasonBattleInfo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SeasonBattleInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SeasonBattleInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SeasonBattleInfoDefaultTypeInternal() {}
  union {
    SeasonBattleInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SeasonBattleInfoDefaultTypeInternal _SeasonBattleInfo_default_instance_;
}  // namespace Next
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_com_5fseason_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_com_5fseason_2eproto = nullptr;
const ::uint32_t
    TableStruct_com_5fseason_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Next::BoxMonsterInfo, _impl_._has_bits_),
        20, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Next::BoxMonsterInfo, _impl_.box_type_),
        PROTOBUF_FIELD_OFFSET(::Next::BoxMonsterInfo, _impl_.is_shiny_),
        PROTOBUF_FIELD_OFFSET(::Next::BoxMonsterInfo, _impl_.is_fantastic_),
        PROTOBUF_FIELD_OFFSET(::Next::BoxMonsterInfo, _impl_.box_conf_id_),
        PROTOBUF_FIELD_OFFSET(::Next::BoxMonsterInfo, _impl_.pet_content_id_),
        PROTOBUF_FIELD_OFFSET(::Next::BoxMonsterInfo, _impl_.is_nightmare_),
        PROTOBUF_FIELD_OFFSET(::Next::BoxMonsterInfo, _impl_.belong_season_),
        PROTOBUF_FIELD_OFFSET(::Next::BoxMonsterInfo, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::Next::BoxMonsterInfo, _impl_.monster_id_),
        PROTOBUF_FIELD_OFFSET(::Next::BoxMonsterInfo, _impl_.pet_rarity_type_),
        PROTOBUF_FIELD_OFFSET(::Next::BoxMonsterInfo, _impl_.pet_mutation_type_),
        PROTOBUF_FIELD_OFFSET(::Next::BoxMonsterInfo, _impl_.pet_nature_),
        PROTOBUF_FIELD_OFFSET(::Next::BoxMonsterInfo, _impl_.gender_),
        PROTOBUF_FIELD_OFFSET(::Next::BoxMonsterInfo, _impl_.height_),
        PROTOBUF_FIELD_OFFSET(::Next::BoxMonsterInfo, _impl_.weight_),
        PROTOBUF_FIELD_OFFSET(::Next::BoxMonsterInfo, _impl_.voice_),
        PROTOBUF_FIELD_OFFSET(::Next::BoxMonsterInfo, _impl_.refresh_batch_id_),
        1,
        2,
        3,
        5,
        6,
        4,
        7,
        0,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        16,
        15,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Next::SeasonPetInfo, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Next::SeasonPetInfo, _impl_.is_nightmare_),
        PROTOBUF_FIELD_OFFSET(::Next::SeasonPetInfo, _impl_.is_shiny_),
        PROTOBUF_FIELD_OFFSET(::Next::SeasonPetInfo, _impl_.is_fantastic_),
        PROTOBUF_FIELD_OFFSET(::Next::SeasonPetInfo, _impl_.mix_blood_),
        PROTOBUF_FIELD_OFFSET(::Next::SeasonPetInfo, _impl_.refresh_batch_id_),
        0,
        1,
        2,
        3,
        4,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Next::SeasonBattleInfo, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Next::SeasonBattleInfo, _impl_.box_info_),
        PROTOBUF_FIELD_OFFSET(::Next::SeasonBattleInfo, _impl_.season_pet_info_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Next::BoxMonsterInfo)},
        {37, sizeof(::Next::SeasonPetInfo)},
        {50, sizeof(::Next::SeasonBattleInfo)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::Next::_BoxMonsterInfo_default_instance_._instance,
    &::Next::_SeasonPetInfo_default_instance_._instance,
    &::Next::_SeasonBattleInfo_default_instance_._instance,
};
const char descriptor_table_protodef_com_5fseason_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020com_season.proto\022\004Next\032\025com_battle_enu"
    "m.proto\032\016xls_enum.proto\"\242\003\n\016BoxMonsterIn"
    "fo\022\037\n\010box_type\030\001 \001(\0162\r.Next.BoxType\022\020\n\010i"
    "s_shiny\030\002 \001(\010\022\024\n\014is_fantastic\030\003 \001(\010\022\023\n\013b"
    "ox_conf_id\030\004 \001(\r\022\026\n\016pet_content_id\030\005 \001(\005"
    "\022\024\n\014is_nightmare\030\006 \001(\010\022\025\n\rbelong_season\030"
    "\007 \001(\005\022\014\n\004name\030\010 \001(\014\022\022\n\nmonster_id\030\t \001(\r\022"
    ",\n\017pet_rarity_type\030\n \001(\0162\023.Next.PetRarit"
    "yType\0220\n\021pet_mutation_type\030\013 \001(\0162\025.Next."
    "PetMutationType\022\022\n\npet_nature\030\014 \001(\005\022\016\n\006g"
    "ender\030\r \001(\r\022\016\n\006height\030\016 \001(\005\022\016\n\006weight\030\017 "
    "\001(\005\022\r\n\005voice\030\020 \001(\005\022\030\n\020refresh_batch_id\030\036"
    " \001(\004\"z\n\rSeasonPetInfo\022\024\n\014is_nightmare\030\001 "
    "\001(\010\022\020\n\010is_shiny\030\002 \001(\010\022\024\n\014is_fantastic\030\003 "
    "\001(\010\022\021\n\tmix_blood\030\004 \001(\005\022\030\n\020refresh_batch_"
    "id\030\024 \001(\004\"h\n\020SeasonBattleInfo\022&\n\010box_info"
    "\030\001 \001(\0132\024.Next.BoxMonsterInfo\022,\n\017season_p"
    "et_info\030\n \001(\0132\023.Next.SeasonPetInfo"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_com_5fseason_2eproto_deps[2] = {
        &::descriptor_table_com_5fbattle_5fenum_2eproto,
        &::descriptor_table_xls_5fenum_2eproto,
};
static ::absl::once_flag descriptor_table_com_5fseason_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_com_5fseason_2eproto = {
    false,
    false,
    714,
    descriptor_table_protodef_com_5fseason_2eproto,
    "com_season.proto",
    &descriptor_table_com_5fseason_2eproto_once,
    descriptor_table_com_5fseason_2eproto_deps,
    2,
    3,
    schemas,
    file_default_instances,
    TableStruct_com_5fseason_2eproto::offsets,
    file_level_enum_descriptors_com_5fseason_2eproto,
    file_level_service_descriptors_com_5fseason_2eproto,
};
namespace Next {
// ===================================================================

class BoxMonsterInfo::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<BoxMonsterInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_._has_bits_);
};

BoxMonsterInfo::BoxMonsterInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BoxMonsterInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Next.BoxMonsterInfo)
}
PROTOBUF_NDEBUG_INLINE BoxMonsterInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Next::BoxMonsterInfo& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

BoxMonsterInfo::BoxMonsterInfo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const BoxMonsterInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BoxMonsterInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BoxMonsterInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, box_type_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, box_type_),
           offsetof(Impl_, voice_) -
               offsetof(Impl_, box_type_) +
               sizeof(Impl_::voice_));

  // @@protoc_insertion_point(copy_constructor:Next.BoxMonsterInfo)
}
PROTOBUF_NDEBUG_INLINE BoxMonsterInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena) {}

inline void BoxMonsterInfo::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, box_type_),
           0,
           offsetof(Impl_, voice_) -
               offsetof(Impl_, box_type_) +
               sizeof(Impl_::voice_));
}
BoxMonsterInfo::~BoxMonsterInfo() {
  // @@protoc_insertion_point(destructor:Next.BoxMonsterInfo)
  SharedDtor(*this);
}
inline void BoxMonsterInfo::SharedDtor(MessageLite& self) {
  BoxMonsterInfo& this_ = static_cast<BoxMonsterInfo&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BoxMonsterInfo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BoxMonsterInfo(arena);
}
constexpr auto BoxMonsterInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(BoxMonsterInfo),
                                            alignof(BoxMonsterInfo));
}
constexpr auto BoxMonsterInfo::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BoxMonsterInfo_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BoxMonsterInfo::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BoxMonsterInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BoxMonsterInfo::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BoxMonsterInfo>(), &BoxMonsterInfo::ByteSizeLong,
              &BoxMonsterInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_._cached_size_),
          false,
      },
      &BoxMonsterInfo::kDescriptorMethods,
      &descriptor_table_com_5fseason_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BoxMonsterInfo_class_data_ =
        BoxMonsterInfo::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BoxMonsterInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BoxMonsterInfo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BoxMonsterInfo_class_data_.tc_table);
  return BoxMonsterInfo_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<5, 17, 3, 0, 2>
BoxMonsterInfo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_._has_bits_),
    0, // no _extensions_
    30, 248,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    3758030848,  // skipmap
    offsetof(decltype(_table_), field_entries),
    17,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    BoxMonsterInfo_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Next::BoxMonsterInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional .Next.BoxType box_type = 1;
    {::_pbi::TcParser::FastEr0S1,
     {8, 1, 3,
      PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.box_type_)}},
    // optional bool is_shiny = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(BoxMonsterInfo, _impl_.is_shiny_), 2>(),
     {16, 2, 0,
      PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.is_shiny_)}},
    // optional bool is_fantastic = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(BoxMonsterInfo, _impl_.is_fantastic_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.is_fantastic_)}},
    // optional uint32 box_conf_id = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BoxMonsterInfo, _impl_.box_conf_id_), 5>(),
     {32, 5, 0,
      PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.box_conf_id_)}},
    // optional int32 pet_content_id = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BoxMonsterInfo, _impl_.pet_content_id_), 6>(),
     {40, 6, 0,
      PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.pet_content_id_)}},
    // optional bool is_nightmare = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(BoxMonsterInfo, _impl_.is_nightmare_), 4>(),
     {48, 4, 0,
      PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.is_nightmare_)}},
    // optional int32 belong_season = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BoxMonsterInfo, _impl_.belong_season_), 7>(),
     {56, 7, 0,
      PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.belong_season_)}},
    // optional bytes name = 8;
    {::_pbi::TcParser::FastBS1,
     {66, 0, 0,
      PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.name_)}},
    // optional uint32 monster_id = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BoxMonsterInfo, _impl_.monster_id_), 8>(),
     {72, 8, 0,
      PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.monster_id_)}},
    // optional .Next.PetRarityType pet_rarity_type = 10;
    {::_pbi::TcParser::FastEr0S1,
     {80, 9, 5,
      PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.pet_rarity_type_)}},
    // optional .Next.PetMutationType pet_mutation_type = 11;
    {::_pbi::TcParser::FastEr0S1,
     {88, 10, 5,
      PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.pet_mutation_type_)}},
    // optional int32 pet_nature = 12;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BoxMonsterInfo, _impl_.pet_nature_), 11>(),
     {96, 11, 0,
      PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.pet_nature_)}},
    // optional uint32 gender = 13;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BoxMonsterInfo, _impl_.gender_), 12>(),
     {104, 12, 0,
      PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.gender_)}},
    // optional int32 height = 14;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BoxMonsterInfo, _impl_.height_), 13>(),
     {112, 13, 0,
      PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.height_)}},
    // optional int32 weight = 15;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BoxMonsterInfo, _impl_.weight_), 14>(),
     {120, 14, 0,
      PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.weight_)}},
    // optional int32 voice = 16;
    {::_pbi::TcParser::FastV32S2,
     {384, 16, 0,
      PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.voice_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // optional uint64 refresh_batch_id = 30;
    {::_pbi::TcParser::FastV64S2,
     {496, 15, 0,
      PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.refresh_batch_id_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .Next.BoxType box_type = 1;
    {PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.box_type_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // optional bool is_shiny = 2;
    {PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.is_shiny_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool is_fantastic = 3;
    {PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.is_fantastic_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional uint32 box_conf_id = 4;
    {PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.box_conf_id_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional int32 pet_content_id = 5;
    {PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.pet_content_id_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional bool is_nightmare = 6;
    {PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.is_nightmare_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional int32 belong_season = 7;
    {PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.belong_season_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional bytes name = 8;
    {PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional uint32 monster_id = 9;
    {PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.monster_id_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional .Next.PetRarityType pet_rarity_type = 10;
    {PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.pet_rarity_type_), _Internal::kHasBitsOffset + 9, 1, (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // optional .Next.PetMutationType pet_mutation_type = 11;
    {PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.pet_mutation_type_), _Internal::kHasBitsOffset + 10, 2, (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // optional int32 pet_nature = 12;
    {PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.pet_nature_), _Internal::kHasBitsOffset + 11, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional uint32 gender = 13;
    {PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.gender_), _Internal::kHasBitsOffset + 12, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional int32 height = 14;
    {PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.height_), _Internal::kHasBitsOffset + 13, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 weight = 15;
    {PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.weight_), _Internal::kHasBitsOffset + 14, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 voice = 16;
    {PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.voice_), _Internal::kHasBitsOffset + 16, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional uint64 refresh_batch_id = 30;
    {PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.refresh_batch_id_), _Internal::kHasBitsOffset + 15, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  {{
      {0, 3},
      {0, 5},
      {0, 5},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void BoxMonsterInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:Next.BoxMonsterInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.name_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000feU)) {
    ::memset(&_impl_.box_type_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.belong_season_) -
        reinterpret_cast<char*>(&_impl_.box_type_)) + sizeof(_impl_.belong_season_));
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000ff00U)) {
    ::memset(&_impl_.monster_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.refresh_batch_id_) -
        reinterpret_cast<char*>(&_impl_.monster_id_)) + sizeof(_impl_.refresh_batch_id_));
  }
  _impl_.voice_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BoxMonsterInfo::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BoxMonsterInfo& this_ = static_cast<const BoxMonsterInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BoxMonsterInfo::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BoxMonsterInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Next.BoxMonsterInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional .Next.BoxType box_type = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this_._internal_box_type(), target);
  }

  // optional bool is_shiny = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this_._internal_is_shiny(), target);
  }

  // optional bool is_fantastic = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        3, this_._internal_is_fantastic(), target);
  }

  // optional uint32 box_conf_id = 4;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this_._internal_box_conf_id(), target);
  }

  // optional int32 pet_content_id = 5;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
            stream, this_._internal_pet_content_id(), target);
  }

  // optional bool is_nightmare = 6;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        6, this_._internal_is_nightmare(), target);
  }

  // optional int32 belong_season = 7;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<7>(
            stream, this_._internal_belong_season(), target);
  }

  // optional bytes name = 8;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_name();
    target = stream->WriteBytesMaybeAliased(8, _s, target);
  }

  // optional uint32 monster_id = 9;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        9, this_._internal_monster_id(), target);
  }

  // optional .Next.PetRarityType pet_rarity_type = 10;
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        10, this_._internal_pet_rarity_type(), target);
  }

  // optional .Next.PetMutationType pet_mutation_type = 11;
  if (CheckHasBit(cached_has_bits, 0x00000400U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        11, this_._internal_pet_mutation_type(), target);
  }

  // optional int32 pet_nature = 12;
  if (CheckHasBit(cached_has_bits, 0x00000800U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<12>(
            stream, this_._internal_pet_nature(), target);
  }

  // optional uint32 gender = 13;
  if (CheckHasBit(cached_has_bits, 0x00001000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        13, this_._internal_gender(), target);
  }

  // optional int32 height = 14;
  if (CheckHasBit(cached_has_bits, 0x00002000U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<14>(
            stream, this_._internal_height(), target);
  }

  // optional int32 weight = 15;
  if (CheckHasBit(cached_has_bits, 0x00004000U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<15>(
            stream, this_._internal_weight(), target);
  }

  // optional int32 voice = 16;
  if (CheckHasBit(cached_has_bits, 0x00010000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        16, this_._internal_voice(), target);
  }

  // optional uint64 refresh_batch_id = 30;
  if (CheckHasBit(cached_has_bits, 0x00008000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        30, this_._internal_refresh_batch_id(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Next.BoxMonsterInfo)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BoxMonsterInfo::ByteSizeLong(const MessageLite& base) {
  const BoxMonsterInfo& this_ = static_cast<const BoxMonsterInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BoxMonsterInfo::ByteSizeLong() const {
  const BoxMonsterInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Next.BoxMonsterInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += ::absl::popcount(0x0000001cU & cached_has_bits) * 2;
  if (BatchCheckHasBit(cached_has_bits, 0x000000e3U)) {
    // optional bytes name = 8;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_name());
    }
    // optional .Next.BoxType box_type = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_box_type());
    }
    // optional uint32 box_conf_id = 4;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_box_conf_id());
    }
    // optional int32 pet_content_id = 5;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_pet_content_id());
    }
    // optional int32 belong_season = 7;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_belong_season());
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000ff00U)) {
    // optional uint32 monster_id = 9;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_monster_id());
    }
    // optional .Next.PetRarityType pet_rarity_type = 10;
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_pet_rarity_type());
    }
    // optional .Next.PetMutationType pet_mutation_type = 11;
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_pet_mutation_type());
    }
    // optional int32 pet_nature = 12;
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_pet_nature());
    }
    // optional uint32 gender = 13;
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_gender());
    }
    // optional int32 height = 14;
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_height());
    }
    // optional int32 weight = 15;
    if (CheckHasBit(cached_has_bits, 0x00004000U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_weight());
    }
    // optional uint64 refresh_batch_id = 30;
    if (CheckHasBit(cached_has_bits, 0x00008000U)) {
      total_size += 2 + ::_pbi::WireFormatLite::UInt64Size(
                                      this_._internal_refresh_batch_id());
    }
  }
   {
    // optional int32 voice = 16;
    if (CheckHasBit(cached_has_bits, 0x00010000U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this_._internal_voice());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BoxMonsterInfo::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<BoxMonsterInfo*>(&to_msg);
  auto& from = static_cast<const BoxMonsterInfo&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Next.BoxMonsterInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_name(from._internal_name());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.box_type_ = from._impl_.box_type_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.is_shiny_ = from._impl_.is_shiny_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.is_fantastic_ = from._impl_.is_fantastic_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.is_nightmare_ = from._impl_.is_nightmare_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.box_conf_id_ = from._impl_.box_conf_id_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _this->_impl_.pet_content_id_ = from._impl_.pet_content_id_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      _this->_impl_.belong_season_ = from._impl_.belong_season_;
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000ff00U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      _this->_impl_.monster_id_ = from._impl_.monster_id_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      _this->_impl_.pet_rarity_type_ = from._impl_.pet_rarity_type_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      _this->_impl_.pet_mutation_type_ = from._impl_.pet_mutation_type_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      _this->_impl_.pet_nature_ = from._impl_.pet_nature_;
    }
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      _this->_impl_.gender_ = from._impl_.gender_;
    }
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      _this->_impl_.height_ = from._impl_.height_;
    }
    if (CheckHasBit(cached_has_bits, 0x00004000U)) {
      _this->_impl_.weight_ = from._impl_.weight_;
    }
    if (CheckHasBit(cached_has_bits, 0x00008000U)) {
      _this->_impl_.refresh_batch_id_ = from._impl_.refresh_batch_id_;
    }
  }
  if (CheckHasBit(cached_has_bits, 0x00010000U)) {
    _this->_impl_.voice_ = from._impl_.voice_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void BoxMonsterInfo::CopyFrom(const BoxMonsterInfo& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Next.BoxMonsterInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BoxMonsterInfo::InternalSwap(BoxMonsterInfo* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.voice_)
      + sizeof(BoxMonsterInfo::_impl_.voice_)
      - PROTOBUF_FIELD_OFFSET(BoxMonsterInfo, _impl_.box_type_)>(
          reinterpret_cast<char*>(&_impl_.box_type_),
          reinterpret_cast<char*>(&other->_impl_.box_type_));
}

::google::protobuf::Metadata BoxMonsterInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SeasonPetInfo::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SeasonPetInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SeasonPetInfo, _impl_._has_bits_);
};

SeasonPetInfo::SeasonPetInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SeasonPetInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Next.SeasonPetInfo)
}
SeasonPetInfo::SeasonPetInfo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SeasonPetInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SeasonPetInfo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE SeasonPetInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void SeasonPetInfo::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, is_nightmare_),
           0,
           offsetof(Impl_, refresh_batch_id_) -
               offsetof(Impl_, is_nightmare_) +
               sizeof(Impl_::refresh_batch_id_));
}
SeasonPetInfo::~SeasonPetInfo() {
  // @@protoc_insertion_point(destructor:Next.SeasonPetInfo)
  SharedDtor(*this);
}
inline void SeasonPetInfo::SharedDtor(MessageLite& self) {
  SeasonPetInfo& this_ = static_cast<SeasonPetInfo&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SeasonPetInfo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SeasonPetInfo(arena);
}
constexpr auto SeasonPetInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SeasonPetInfo),
                                            alignof(SeasonPetInfo));
}
constexpr auto SeasonPetInfo::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SeasonPetInfo_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SeasonPetInfo::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SeasonPetInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SeasonPetInfo::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SeasonPetInfo>(), &SeasonPetInfo::ByteSizeLong,
              &SeasonPetInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SeasonPetInfo, _impl_._cached_size_),
          false,
      },
      &SeasonPetInfo::kDescriptorMethods,
      &descriptor_table_com_5fseason_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SeasonPetInfo_class_data_ =
        SeasonPetInfo::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SeasonPetInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SeasonPetInfo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SeasonPetInfo_class_data_.tc_table);
  return SeasonPetInfo_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 5, 0, 0, 2>
SeasonPetInfo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SeasonPetInfo, _impl_._has_bits_),
    0, // no _extensions_
    20, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294442992,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SeasonPetInfo_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Next::SeasonPetInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int32 mix_blood = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SeasonPetInfo, _impl_.mix_blood_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(SeasonPetInfo, _impl_.mix_blood_)}},
    // optional bool is_nightmare = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SeasonPetInfo, _impl_.is_nightmare_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(SeasonPetInfo, _impl_.is_nightmare_)}},
    // optional bool is_shiny = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SeasonPetInfo, _impl_.is_shiny_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(SeasonPetInfo, _impl_.is_shiny_)}},
    // optional bool is_fantastic = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SeasonPetInfo, _impl_.is_fantastic_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(SeasonPetInfo, _impl_.is_fantastic_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional bool is_nightmare = 1;
    {PROTOBUF_FIELD_OFFSET(SeasonPetInfo, _impl_.is_nightmare_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool is_shiny = 2;
    {PROTOBUF_FIELD_OFFSET(SeasonPetInfo, _impl_.is_shiny_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool is_fantastic = 3;
    {PROTOBUF_FIELD_OFFSET(SeasonPetInfo, _impl_.is_fantastic_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional int32 mix_blood = 4;
    {PROTOBUF_FIELD_OFFSET(SeasonPetInfo, _impl_.mix_blood_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional uint64 refresh_batch_id = 20;
    {PROTOBUF_FIELD_OFFSET(SeasonPetInfo, _impl_.refresh_batch_id_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void SeasonPetInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:Next.SeasonPetInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    ::memset(&_impl_.is_nightmare_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.refresh_batch_id_) -
        reinterpret_cast<char*>(&_impl_.is_nightmare_)) + sizeof(_impl_.refresh_batch_id_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SeasonPetInfo::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SeasonPetInfo& this_ = static_cast<const SeasonPetInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SeasonPetInfo::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SeasonPetInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Next.SeasonPetInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional bool is_nightmare = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this_._internal_is_nightmare(), target);
  }

  // optional bool is_shiny = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this_._internal_is_shiny(), target);
  }

  // optional bool is_fantastic = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        3, this_._internal_is_fantastic(), target);
  }

  // optional int32 mix_blood = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<4>(
            stream, this_._internal_mix_blood(), target);
  }

  // optional uint64 refresh_batch_id = 20;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        20, this_._internal_refresh_batch_id(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Next.SeasonPetInfo)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SeasonPetInfo::ByteSizeLong(const MessageLite& base) {
  const SeasonPetInfo& this_ = static_cast<const SeasonPetInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SeasonPetInfo::ByteSizeLong() const {
  const SeasonPetInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Next.SeasonPetInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += ::absl::popcount(0x00000007U & cached_has_bits) * 2;
  if (BatchCheckHasBit(cached_has_bits, 0x00000018U)) {
    // optional int32 mix_blood = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_mix_blood());
    }
    // optional uint64 refresh_batch_id = 20;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += 2 + ::_pbi::WireFormatLite::UInt64Size(
                                      this_._internal_refresh_batch_id());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SeasonPetInfo::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SeasonPetInfo*>(&to_msg);
  auto& from = static_cast<const SeasonPetInfo&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Next.SeasonPetInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.is_nightmare_ = from._impl_.is_nightmare_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.is_shiny_ = from._impl_.is_shiny_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.is_fantastic_ = from._impl_.is_fantastic_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.mix_blood_ = from._impl_.mix_blood_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.refresh_batch_id_ = from._impl_.refresh_batch_id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SeasonPetInfo::CopyFrom(const SeasonPetInfo& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Next.SeasonPetInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SeasonPetInfo::InternalSwap(SeasonPetInfo* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SeasonPetInfo, _impl_.refresh_batch_id_)
      + sizeof(SeasonPetInfo::_impl_.refresh_batch_id_)
      - PROTOBUF_FIELD_OFFSET(SeasonPetInfo, _impl_.is_nightmare_)>(
          reinterpret_cast<char*>(&_impl_.is_nightmare_),
          reinterpret_cast<char*>(&other->_impl_.is_nightmare_));
}

::google::protobuf::Metadata SeasonPetInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SeasonBattleInfo::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SeasonBattleInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SeasonBattleInfo, _impl_._has_bits_);
};

SeasonBattleInfo::SeasonBattleInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SeasonBattleInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Next.SeasonBattleInfo)
}
PROTOBUF_NDEBUG_INLINE SeasonBattleInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Next::SeasonBattleInfo& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

SeasonBattleInfo::SeasonBattleInfo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SeasonBattleInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SeasonBattleInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SeasonBattleInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.box_info_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.box_info_)
                : nullptr;
  _impl_.season_pet_info_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.season_pet_info_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:Next.SeasonBattleInfo)
}
PROTOBUF_NDEBUG_INLINE SeasonBattleInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void SeasonBattleInfo::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, box_info_),
           0,
           offsetof(Impl_, season_pet_info_) -
               offsetof(Impl_, box_info_) +
               sizeof(Impl_::season_pet_info_));
}
SeasonBattleInfo::~SeasonBattleInfo() {
  // @@protoc_insertion_point(destructor:Next.SeasonBattleInfo)
  SharedDtor(*this);
}
inline void SeasonBattleInfo::SharedDtor(MessageLite& self) {
  SeasonBattleInfo& this_ = static_cast<SeasonBattleInfo&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.box_info_;
  delete this_._impl_.season_pet_info_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SeasonBattleInfo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SeasonBattleInfo(arena);
}
constexpr auto SeasonBattleInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SeasonBattleInfo),
                                            alignof(SeasonBattleInfo));
}
constexpr auto SeasonBattleInfo::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SeasonBattleInfo_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SeasonBattleInfo::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SeasonBattleInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SeasonBattleInfo::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SeasonBattleInfo>(), &SeasonBattleInfo::ByteSizeLong,
              &SeasonBattleInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SeasonBattleInfo, _impl_._cached_size_),
          false,
      },
      &SeasonBattleInfo::kDescriptorMethods,
      &descriptor_table_com_5fseason_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SeasonBattleInfo_class_data_ =
        SeasonBattleInfo::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SeasonBattleInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SeasonBattleInfo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SeasonBattleInfo_class_data_.tc_table);
  return SeasonBattleInfo_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2>
SeasonBattleInfo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SeasonBattleInfo, _impl_._has_bits_),
    0, // no _extensions_
    10, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966782,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    SeasonBattleInfo_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Next::SeasonBattleInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional .Next.SeasonPetInfo season_pet_info = 10;
    {::_pbi::TcParser::FastMtS1,
     {82, 1, 1,
      PROTOBUF_FIELD_OFFSET(SeasonBattleInfo, _impl_.season_pet_info_)}},
    // optional .Next.BoxMonsterInfo box_info = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(SeasonBattleInfo, _impl_.box_info_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .Next.BoxMonsterInfo box_info = 1;
    {PROTOBUF_FIELD_OFFSET(SeasonBattleInfo, _impl_.box_info_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .Next.SeasonPetInfo season_pet_info = 10;
    {PROTOBUF_FIELD_OFFSET(SeasonBattleInfo, _impl_.season_pet_info_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::Next::BoxMonsterInfo>()},
      {::_pbi::TcParser::GetTable<::Next::SeasonPetInfo>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void SeasonBattleInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:Next.SeasonBattleInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(_impl_.box_info_ != nullptr);
      _impl_.box_info_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.season_pet_info_ != nullptr);
      _impl_.season_pet_info_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SeasonBattleInfo::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SeasonBattleInfo& this_ = static_cast<const SeasonBattleInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SeasonBattleInfo::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SeasonBattleInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Next.SeasonBattleInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional .Next.BoxMonsterInfo box_info = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.box_info_, this_._impl_.box_info_->GetCachedSize(), target,
        stream);
  }

  // optional .Next.SeasonPetInfo season_pet_info = 10;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        10, *this_._impl_.season_pet_info_, this_._impl_.season_pet_info_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Next.SeasonBattleInfo)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SeasonBattleInfo::ByteSizeLong(const MessageLite& base) {
  const SeasonBattleInfo& this_ = static_cast<const SeasonBattleInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SeasonBattleInfo::ByteSizeLong() const {
  const SeasonBattleInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Next.SeasonBattleInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // optional .Next.BoxMonsterInfo box_info = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.box_info_);
    }
    // optional .Next.SeasonPetInfo season_pet_info = 10;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.season_pet_info_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SeasonBattleInfo::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SeasonBattleInfo*>(&to_msg);
  auto& from = static_cast<const SeasonBattleInfo&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Next.SeasonBattleInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.box_info_ != nullptr);
      if (_this->_impl_.box_info_ == nullptr) {
        _this->_impl_.box_info_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.box_info_);
      } else {
        _this->_impl_.box_info_->MergeFrom(*from._impl_.box_info_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.season_pet_info_ != nullptr);
      if (_this->_impl_.season_pet_info_ == nullptr) {
        _this->_impl_.season_pet_info_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.season_pet_info_);
      } else {
        _this->_impl_.season_pet_info_->MergeFrom(*from._impl_.season_pet_info_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SeasonBattleInfo::CopyFrom(const SeasonBattleInfo& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Next.SeasonBattleInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SeasonBattleInfo::InternalSwap(SeasonBattleInfo* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SeasonBattleInfo, _impl_.season_pet_info_)
      + sizeof(SeasonBattleInfo::_impl_.season_pet_info_)
      - PROTOBUF_FIELD_OFFSET(SeasonBattleInfo, _impl_.box_info_)>(
          reinterpret_cast<char*>(&_impl_.box_info_),
          reinterpret_cast<char*>(&other->_impl_.box_info_));
}

::google::protobuf::Metadata SeasonBattleInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Next
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_com_5fseason_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
