// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpc_options.proto
// Protobuf C++ Version: 6.33.6

#include "rpc_options.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
template <typename>
PROTOBUF_CONSTEXPR NullResponse::NullResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(NullResponse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct NullResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NullResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NullResponseDefaultTypeInternal() {}
  union {
    NullResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NullResponseDefaultTypeInternal _NullResponse_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR NullRequest::NullRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(NullRequest_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct NullRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NullRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NullRequestDefaultTypeInternal() {}
  union {
    NullRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NullRequestDefaultTypeInternal _NullRequest_default_instance_;
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_rpc_5foptions_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_rpc_5foptions_2eproto = nullptr;
const ::uint32_t
    TableStruct_rpc_5foptions_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
        0x000, // bitmap
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::NullRequest)},
        {1, sizeof(::NullResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_NullRequest_default_instance_._instance,
    &::_NullResponse_default_instance_._instance,
};
const char descriptor_table_protodef_rpc_5foptions_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021rpc_options.proto\032 google/protobuf/des"
    "criptor.proto\"\r\n\013NullRequest\"\016\n\014NullResp"
    "onse*G\n\rRealTypeOfInt\022\014\n\010RT_UINT8\020\001\022\013\n\007R"
    "T_INT8\020\002\022\r\n\tRT_UINT16\020\003\022\014\n\010RT_INT16\020\004"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_rpc_5foptions_2eproto_deps[1] = {
        &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::absl::once_flag descriptor_table_rpc_5foptions_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_rpc_5foptions_2eproto = {
    false,
    false,
    157,
    descriptor_table_protodef_rpc_5foptions_2eproto,
    "rpc_options.proto",
    &descriptor_table_rpc_5foptions_2eproto_once,
    descriptor_table_rpc_5foptions_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_rpc_5foptions_2eproto::offsets,
    file_level_enum_descriptors_rpc_5foptions_2eproto,
    file_level_service_descriptors_rpc_5foptions_2eproto,
};
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL RealTypeOfInt_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_rpc_5foptions_2eproto);
  return file_level_enum_descriptors_rpc_5foptions_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t RealTypeOfInt_internal_data_[] = {
    262145u, 0u, };
// ===================================================================

class NullRequest::_Internal {
 public:
};

NullRequest::NullRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, NullRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:NullRequest)
}
NullRequest::NullRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const NullRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, NullRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NullRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:NullRequest)
}

inline void* PROTOBUF_NONNULL NullRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NullRequest(arena);
}
constexpr auto NullRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(NullRequest),
                                            alignof(NullRequest));
}
constexpr auto NullRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NullRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &NullRequest::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<NullRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NullRequest::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<NullRequest>(), &NullRequest::ByteSizeLong,
              &NullRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NullRequest, _impl_._cached_size_),
          false,
      },
      &NullRequest::kDescriptorMethods,
      &descriptor_table_rpc_5foptions_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NullRequest_class_data_ =
        NullRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NullRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NullRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NullRequest_class_data_.tc_table);
  return NullRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
NullRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    NullRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NullRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata NullRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NullResponse::_Internal {
 public:
};

NullResponse::NullResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, NullResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:NullResponse)
}
NullResponse::NullResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const NullResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, NullResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NullResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:NullResponse)
}

inline void* PROTOBUF_NONNULL NullResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NullResponse(arena);
}
constexpr auto NullResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(NullResponse),
                                            alignof(NullResponse));
}
constexpr auto NullResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NullResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &NullResponse::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<NullResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NullResponse::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<NullResponse>(), &NullResponse::ByteSizeLong,
              &NullResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NullResponse, _impl_._cached_size_),
          false,
      },
      &NullResponse::kDescriptorMethods,
      &descriptor_table_rpc_5foptions_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NullResponse_class_data_ =
        NullResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NullResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NullResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NullResponse_class_data_.tc_table);
  return NullResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
NullResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    NullResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NullResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata NullResponse::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_rpc_5foptions_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
