// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: space_enum.proto
// Protobuf C++ Version: 7.35.0

#include "space_enum.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::Next::SpaceEnum_SpaceObjType
        {&::_pbi::kDescriptorMethods, &::descriptor_table_space_5fenum_2eproto, /* tracker*/ nullptr,},
        // ::Next::SpaceEnum_SpaceObjSubType
        {&::_pbi::kDescriptorMethods, &::descriptor_table_space_5fenum_2eproto, /* tracker*/ nullptr,},
        // ::Next::SpaceEnum_ActorDetailType
        {&::_pbi::kDescriptorMethods, &::descriptor_table_space_5fenum_2eproto, /* tracker*/ nullptr,},
        // ::Next::SpaceEnum_AvatarSceneChangeReason
        {&::_pbi::kDescriptorMethods, &::descriptor_table_space_5fenum_2eproto, /* tracker*/ nullptr,},
        // ::Next::SpaceEnum_NpcRefreshSource
        {&::_pbi::kDescriptorMethods, &::descriptor_table_space_5fenum_2eproto, /* tracker*/ nullptr,},
        // ::Next::SpaceEnum_ActorMoveMode
        {&::_pbi::kDescriptorMethods, &::descriptor_table_space_5fenum_2eproto, /* tracker*/ nullptr,},
        // ::Next::SpaceEnum_NpcActionStatus
        {&::_pbi::kDescriptorMethods, &::descriptor_table_space_5fenum_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace Next {
class SpaceEnum_SpaceObjType::_Internal {
 public:
};

constexpr SpaceEnum_SpaceObjType::ParseTableT_ SpaceEnum_SpaceObjType::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(SpaceEnum_SpaceObjType,
                            _impl_._cached_size_),  // no hasbits
      0, // no _extensions_
      0, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967295,  // skipmap
      offsetof(ParseTableT_, field_names),  // no field_entries
      0,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::Next::SpaceEnum_SpaceObjType>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, // no field_entries, or aux_entries
    {{
    }},
  };
}

template <typename>
constexpr SpaceEnum_SpaceObjType::SpaceEnum_SpaceObjType(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::internal::ZeroFieldsBase(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL SpaceEnum_SpaceObjType::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SpaceEnum_SpaceObjType(arena);
}
constexpr auto SpaceEnum_SpaceObjType::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SpaceEnum_SpaceObjType), alignof(SpaceEnum_SpaceObjType));
}
constexpr auto SpaceEnum_SpaceObjType::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &SpaceEnum_SpaceObjType::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<SpaceEnum_SpaceObjType>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SpaceEnum_SpaceObjType::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<SpaceEnum_SpaceObjType>(), &SpaceEnum_SpaceObjType::ByteSizeLong,
              &SpaceEnum_SpaceObjType::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SpaceEnum_SpaceObjType, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_space_5fenum_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct SpaceEnum_SpaceObjTypeGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr SpaceEnum_SpaceObjTypeGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 SpaceEnum_SpaceObjType_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(SpaceEnum_SpaceObjType::InternalGenerateClassData_(
            _default, &SpaceEnum_SpaceObjType_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<SpaceEnum_SpaceObjType>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~SpaceEnum_SpaceObjTypeGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) SpaceEnum_SpaceObjType _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<SpaceEnum_SpaceObjType>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(SpaceEnum_SpaceObjTypeGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST SpaceEnum_SpaceObjTypeGlobalsTypeInternal SpaceEnum_SpaceObjType_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* SpaceEnum_SpaceObjType_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return SpaceEnum_SpaceObjType_globals_.GetClassData();
#else
  return SpaceEnum_SpaceObjType_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class SpaceEnum_SpaceObjSubType::_Internal {
 public:
};

constexpr SpaceEnum_SpaceObjSubType::ParseTableT_ SpaceEnum_SpaceObjSubType::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(SpaceEnum_SpaceObjSubType,
                            _impl_._cached_size_),  // no hasbits
      0, // no _extensions_
      0, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967295,  // skipmap
      offsetof(ParseTableT_, field_names),  // no field_entries
      0,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::Next::SpaceEnum_SpaceObjSubType>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, // no field_entries, or aux_entries
    {{
    }},
  };
}

template <typename>
constexpr SpaceEnum_SpaceObjSubType::SpaceEnum_SpaceObjSubType(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::internal::ZeroFieldsBase(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL SpaceEnum_SpaceObjSubType::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SpaceEnum_SpaceObjSubType(arena);
}
constexpr auto SpaceEnum_SpaceObjSubType::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SpaceEnum_SpaceObjSubType), alignof(SpaceEnum_SpaceObjSubType));
}
constexpr auto SpaceEnum_SpaceObjSubType::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &SpaceEnum_SpaceObjSubType::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<SpaceEnum_SpaceObjSubType>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SpaceEnum_SpaceObjSubType::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<SpaceEnum_SpaceObjSubType>(), &SpaceEnum_SpaceObjSubType::ByteSizeLong,
              &SpaceEnum_SpaceObjSubType::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SpaceEnum_SpaceObjSubType, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_space_5fenum_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct SpaceEnum_SpaceObjSubTypeGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr SpaceEnum_SpaceObjSubTypeGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 SpaceEnum_SpaceObjSubType_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(SpaceEnum_SpaceObjSubType::InternalGenerateClassData_(
            _default, &SpaceEnum_SpaceObjSubType_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<SpaceEnum_SpaceObjSubType>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~SpaceEnum_SpaceObjSubTypeGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) SpaceEnum_SpaceObjSubType _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<SpaceEnum_SpaceObjSubType>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(SpaceEnum_SpaceObjSubTypeGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST SpaceEnum_SpaceObjSubTypeGlobalsTypeInternal SpaceEnum_SpaceObjSubType_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* SpaceEnum_SpaceObjSubType_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return SpaceEnum_SpaceObjSubType_globals_.GetClassData();
#else
  return SpaceEnum_SpaceObjSubType_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class SpaceEnum_NpcRefreshSource::_Internal {
 public:
};

constexpr SpaceEnum_NpcRefreshSource::ParseTableT_ SpaceEnum_NpcRefreshSource::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(SpaceEnum_NpcRefreshSource,
                            _impl_._cached_size_),  // no hasbits
      0, // no _extensions_
      0, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967295,  // skipmap
      offsetof(ParseTableT_, field_names),  // no field_entries
      0,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::Next::SpaceEnum_NpcRefreshSource>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, // no field_entries, or aux_entries
    {{
    }},
  };
}

template <typename>
constexpr SpaceEnum_NpcRefreshSource::SpaceEnum_NpcRefreshSource(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::internal::ZeroFieldsBase(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL SpaceEnum_NpcRefreshSource::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SpaceEnum_NpcRefreshSource(arena);
}
constexpr auto SpaceEnum_NpcRefreshSource::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SpaceEnum_NpcRefreshSource), alignof(SpaceEnum_NpcRefreshSource));
}
constexpr auto SpaceEnum_NpcRefreshSource::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &SpaceEnum_NpcRefreshSource::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<SpaceEnum_NpcRefreshSource>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SpaceEnum_NpcRefreshSource::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<SpaceEnum_NpcRefreshSource>(), &SpaceEnum_NpcRefreshSource::ByteSizeLong,
              &SpaceEnum_NpcRefreshSource::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SpaceEnum_NpcRefreshSource, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[4],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_space_5fenum_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct SpaceEnum_NpcRefreshSourceGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr SpaceEnum_NpcRefreshSourceGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 SpaceEnum_NpcRefreshSource_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(SpaceEnum_NpcRefreshSource::InternalGenerateClassData_(
            _default, &SpaceEnum_NpcRefreshSource_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<SpaceEnum_NpcRefreshSource>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~SpaceEnum_NpcRefreshSourceGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) SpaceEnum_NpcRefreshSource _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<SpaceEnum_NpcRefreshSource>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(SpaceEnum_NpcRefreshSourceGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST SpaceEnum_NpcRefreshSourceGlobalsTypeInternal SpaceEnum_NpcRefreshSource_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* SpaceEnum_NpcRefreshSource_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return SpaceEnum_NpcRefreshSource_globals_.GetClassData();
#else
  return SpaceEnum_NpcRefreshSource_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class SpaceEnum_NpcActionStatus::_Internal {
 public:
};

constexpr SpaceEnum_NpcActionStatus::ParseTableT_ SpaceEnum_NpcActionStatus::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(SpaceEnum_NpcActionStatus,
                            _impl_._cached_size_),  // no hasbits
      0, // no _extensions_
      0, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967295,  // skipmap
      offsetof(ParseTableT_, field_names),  // no field_entries
      0,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::Next::SpaceEnum_NpcActionStatus>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, // no field_entries, or aux_entries
    {{
    }},
  };
}

template <typename>
constexpr SpaceEnum_NpcActionStatus::SpaceEnum_NpcActionStatus(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::internal::ZeroFieldsBase(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL SpaceEnum_NpcActionStatus::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SpaceEnum_NpcActionStatus(arena);
}
constexpr auto SpaceEnum_NpcActionStatus::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SpaceEnum_NpcActionStatus), alignof(SpaceEnum_NpcActionStatus));
}
constexpr auto SpaceEnum_NpcActionStatus::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &SpaceEnum_NpcActionStatus::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<SpaceEnum_NpcActionStatus>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SpaceEnum_NpcActionStatus::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<SpaceEnum_NpcActionStatus>(), &SpaceEnum_NpcActionStatus::ByteSizeLong,
              &SpaceEnum_NpcActionStatus::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SpaceEnum_NpcActionStatus, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[6],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_space_5fenum_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct SpaceEnum_NpcActionStatusGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr SpaceEnum_NpcActionStatusGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 SpaceEnum_NpcActionStatus_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(SpaceEnum_NpcActionStatus::InternalGenerateClassData_(
            _default, &SpaceEnum_NpcActionStatus_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<SpaceEnum_NpcActionStatus>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~SpaceEnum_NpcActionStatusGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) SpaceEnum_NpcActionStatus _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<SpaceEnum_NpcActionStatus>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(SpaceEnum_NpcActionStatusGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST SpaceEnum_NpcActionStatusGlobalsTypeInternal SpaceEnum_NpcActionStatus_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* SpaceEnum_NpcActionStatus_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return SpaceEnum_NpcActionStatus_globals_.GetClassData();
#else
  return SpaceEnum_NpcActionStatus_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class SpaceEnum_AvatarSceneChangeReason::_Internal {
 public:
};

constexpr SpaceEnum_AvatarSceneChangeReason::ParseTableT_ SpaceEnum_AvatarSceneChangeReason::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(SpaceEnum_AvatarSceneChangeReason,
                            _impl_._cached_size_),  // no hasbits
      0, // no _extensions_
      0, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967295,  // skipmap
      offsetof(ParseTableT_, field_names),  // no field_entries
      0,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::Next::SpaceEnum_AvatarSceneChangeReason>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, // no field_entries, or aux_entries
    {{
    }},
  };
}

template <typename>
constexpr SpaceEnum_AvatarSceneChangeReason::SpaceEnum_AvatarSceneChangeReason(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::internal::ZeroFieldsBase(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL SpaceEnum_AvatarSceneChangeReason::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SpaceEnum_AvatarSceneChangeReason(arena);
}
constexpr auto SpaceEnum_AvatarSceneChangeReason::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SpaceEnum_AvatarSceneChangeReason), alignof(SpaceEnum_AvatarSceneChangeReason));
}
constexpr auto SpaceEnum_AvatarSceneChangeReason::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &SpaceEnum_AvatarSceneChangeReason::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<SpaceEnum_AvatarSceneChangeReason>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SpaceEnum_AvatarSceneChangeReason::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<SpaceEnum_AvatarSceneChangeReason>(), &SpaceEnum_AvatarSceneChangeReason::ByteSizeLong,
              &SpaceEnum_AvatarSceneChangeReason::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SpaceEnum_AvatarSceneChangeReason, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[3],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_space_5fenum_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct SpaceEnum_AvatarSceneChangeReasonGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr SpaceEnum_AvatarSceneChangeReasonGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 SpaceEnum_AvatarSceneChangeReason_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(SpaceEnum_AvatarSceneChangeReason::InternalGenerateClassData_(
            _default, &SpaceEnum_AvatarSceneChangeReason_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<SpaceEnum_AvatarSceneChangeReason>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~SpaceEnum_AvatarSceneChangeReasonGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) SpaceEnum_AvatarSceneChangeReason _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<SpaceEnum_AvatarSceneChangeReason>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(SpaceEnum_AvatarSceneChangeReasonGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST SpaceEnum_AvatarSceneChangeReasonGlobalsTypeInternal SpaceEnum_AvatarSceneChangeReason_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* SpaceEnum_AvatarSceneChangeReason_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return SpaceEnum_AvatarSceneChangeReason_globals_.GetClassData();
#else
  return SpaceEnum_AvatarSceneChangeReason_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class SpaceEnum_ActorMoveMode::_Internal {
 public:
};

constexpr SpaceEnum_ActorMoveMode::ParseTableT_ SpaceEnum_ActorMoveMode::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(SpaceEnum_ActorMoveMode,
                            _impl_._cached_size_),  // no hasbits
      0, // no _extensions_
      0, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967295,  // skipmap
      offsetof(ParseTableT_, field_names),  // no field_entries
      0,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::Next::SpaceEnum_ActorMoveMode>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, // no field_entries, or aux_entries
    {{
    }},
  };
}

template <typename>
constexpr SpaceEnum_ActorMoveMode::SpaceEnum_ActorMoveMode(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::internal::ZeroFieldsBase(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL SpaceEnum_ActorMoveMode::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SpaceEnum_ActorMoveMode(arena);
}
constexpr auto SpaceEnum_ActorMoveMode::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SpaceEnum_ActorMoveMode), alignof(SpaceEnum_ActorMoveMode));
}
constexpr auto SpaceEnum_ActorMoveMode::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &SpaceEnum_ActorMoveMode::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<SpaceEnum_ActorMoveMode>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SpaceEnum_ActorMoveMode::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<SpaceEnum_ActorMoveMode>(), &SpaceEnum_ActorMoveMode::ByteSizeLong,
              &SpaceEnum_ActorMoveMode::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SpaceEnum_ActorMoveMode, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[5],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_space_5fenum_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct SpaceEnum_ActorMoveModeGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr SpaceEnum_ActorMoveModeGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 SpaceEnum_ActorMoveMode_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(SpaceEnum_ActorMoveMode::InternalGenerateClassData_(
            _default, &SpaceEnum_ActorMoveMode_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<SpaceEnum_ActorMoveMode>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~SpaceEnum_ActorMoveModeGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) SpaceEnum_ActorMoveMode _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<SpaceEnum_ActorMoveMode>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(SpaceEnum_ActorMoveModeGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST SpaceEnum_ActorMoveModeGlobalsTypeInternal SpaceEnum_ActorMoveMode_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* SpaceEnum_ActorMoveMode_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return SpaceEnum_ActorMoveMode_globals_.GetClassData();
#else
  return SpaceEnum_ActorMoveMode_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class SpaceEnum_ActorDetailType::_Internal {
 public:
};

constexpr SpaceEnum_ActorDetailType::ParseTableT_ SpaceEnum_ActorDetailType::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(SpaceEnum_ActorDetailType,
                            _impl_._cached_size_),  // no hasbits
      0, // no _extensions_
      0, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967295,  // skipmap
      offsetof(ParseTableT_, field_names),  // no field_entries
      0,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::Next::SpaceEnum_ActorDetailType>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, // no field_entries, or aux_entries
    {{
    }},
  };
}

template <typename>
constexpr SpaceEnum_ActorDetailType::SpaceEnum_ActorDetailType(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::internal::ZeroFieldsBase(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL SpaceEnum_ActorDetailType::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SpaceEnum_ActorDetailType(arena);
}
constexpr auto SpaceEnum_ActorDetailType::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SpaceEnum_ActorDetailType), alignof(SpaceEnum_ActorDetailType));
}
constexpr auto SpaceEnum_ActorDetailType::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &SpaceEnum_ActorDetailType::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<SpaceEnum_ActorDetailType>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SpaceEnum_ActorDetailType::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<SpaceEnum_ActorDetailType>(), &SpaceEnum_ActorDetailType::ByteSizeLong,
              &SpaceEnum_ActorDetailType::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SpaceEnum_ActorDetailType, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[2],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_space_5fenum_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct SpaceEnum_ActorDetailTypeGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr SpaceEnum_ActorDetailTypeGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 SpaceEnum_ActorDetailType_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(SpaceEnum_ActorDetailType::InternalGenerateClassData_(
            _default, &SpaceEnum_ActorDetailType_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<SpaceEnum_ActorDetailType>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~SpaceEnum_ActorDetailTypeGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) SpaceEnum_ActorDetailType _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<SpaceEnum_ActorDetailType>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(SpaceEnum_ActorDetailTypeGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST SpaceEnum_ActorDetailTypeGlobalsTypeInternal SpaceEnum_ActorDetailType_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* SpaceEnum_ActorDetailType_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return SpaceEnum_ActorDetailType_globals_.GetClassData();
#else
  return SpaceEnum_ActorDetailType_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace Next
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_space_5fenum_2eproto[7];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_space_5fenum_2eproto = nullptr;
const ::uint32_t
    TableStruct_space_5fenum_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
        0x000, // bitmap
        0x000, // bitmap
        0x000, // bitmap
        0x000, // bitmap
        0x000, // bitmap
        0x000, // bitmap
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Next::SpaceEnum_SpaceObjType)},
        {1, sizeof(::Next::SpaceEnum_SpaceObjSubType)},
        {2, sizeof(::Next::SpaceEnum_ActorDetailType)},
        {3, sizeof(::Next::SpaceEnum_AvatarSceneChangeReason)},
        {4, sizeof(::Next::SpaceEnum_NpcRefreshSource)},
        {5, sizeof(::Next::SpaceEnum_ActorMoveMode)},
        {6, sizeof(::Next::SpaceEnum_NpcActionStatus)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::Next::SpaceEnum_SpaceObjType_globals_,
        &::Next::SpaceEnum_SpaceObjSubType_globals_,
        &::Next::SpaceEnum_ActorDetailType_globals_,
        &::Next::SpaceEnum_AvatarSceneChangeReason_globals_,
        &::Next::SpaceEnum_NpcRefreshSource_globals_,
        &::Next::SpaceEnum_ActorMoveMode_globals_,
        &::Next::SpaceEnum_NpcActionStatus_globals_,
};
const char descriptor_table_protodef_space_5fenum_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020space_enum.proto\022\004Next\"N\n\026SpaceEnum_Sp"
    "aceObjType\"4\n\004ENUM\022\014\n\010SceneMgr\020\001\022\t\n\005Scen"
    "e\020\002\022\010\n\004Cell\020\003\022\t\n\005Actor\020\004\"\237\001\n\031SpaceEnum_S"
    "paceObjSubType\"\201\001\n\004ENUM\022\023\n\017SceneMgr_Norm"
    "al\020\001\022\020\n\014Scene_Normal\020\002\022\017\n\013Cell_Normal\020\004\022"
    "\020\n\014Actor_Avatar\020\007\022\r\n\tActor_Npc\020\010\022\r\n\tActo"
    "r_Pet\020\t\022\021\n\rActor_Monster\020\n\"\250\002\n\031SpaceEnum"
    "_ActorDetailType\"\212\002\n\004ENUM\022\021\n\rAvatar_Norm"
    "al\020\001\022\022\n\016Avatar_Unused1\020\002\022\022\n\016Avatar_Unuse"
    "d2\020\003\022\017\n\013Npc_Unused1\020\004\022\017\n\013Npc_Unused2\020\005\022\r"
    "\n\tNpc_Scene\020\006\022\020\n\014Npc_DropItem\020\007\022\017\n\013Npc_U"
    "nused3\020\010\022\013\n\007Npc_Pet\020\t\022\017\n\013Npc_HomePet\020\n\022\021"
    "\n\rNpc_HomePlant\020\013\022\014\n\010Npc_Seat\020\014\022\022\n\016Npc_H"
    "omePetEgg\020\r\022\017\n\013Npc_Unused4\020\016\022\017\n\013Npc_Unus"
    "ed5\020\017\"V\n!SpaceEnum_AvatarSceneChangeReas"
    "on\"1\n\004ENUM\022\t\n\005Login\020\001\022\r\n\tReconnect\020\002\022\017\n\013"
    "SwitchScene\020\003\"\242\007\n\032SpaceEnum_NpcRefreshSo"
    "urce\"\203\007\n\004ENUM\022\010\n\004None\020\000\022\n\n\006Normal\020\001\022\010\n\004T"
    "ask\020\002\022\014\n\010Minigame\020\003\022\025\n\021MinigameRewardNpc"
    "\020\004\022\r\n\tOwlRefuge\020\005\022\024\n\020StarHitDirection\020\006\022"
    "\013\n\007Dungeon\020\007\022\006\n\002GM\020\010\022\031\n\025NpcInteract_Open"
    "Chest\020\013\022\032\n\026NpcInteract_TouchLight\020\014\022\032\n\026N"
    "pcInteract_TouchStone\020\r\022\031\n\025NpcInteract_S"
    "hakeTree\020\016\022\037\n\033NpcInteract_OptionCreateNp"
    "c\020\017\022\034\n\030NpcInteract_SubmitPetNpc\020\020\022\035\n\031Npc"
    "Interact_SubmitItemNpc\020\021\022\034\n\030NpcInteract_"
    "PlaySequence\020\022\022\035\n\031NpcInteract_MiracleCha"
    "nge\020\023\022\031\n\025NpcInteract_WonderPea\020\025\022\033\n\027NpcI"
    "nteract_CampLevelup\020\026\022\034\n\030NpcInteract_Cam"
    "pPetFruit\020\027\022$\n NpcInteract_OwlSanctuaryP"
    "etFruit\020\030\022\035\n\031NpcInteract_MagicTransfer\020\031"
    "\022+\n\'NpcInteract_OptionCreateNpcWithAnimP"
    "lay\020\036\022\n\n\006Battle\020\037\022\023\n\017WorldBossReward\020 \022\020"
    "\n\014ThrowBagItem\020)\022\014\n\010ThrowPet\020*\022\016\n\nThrowM"
    "agic\020+\022\017\n\013Combination\0203\022\023\n\017CombineResetN"
    "pc\0204\022\023\n\017ControllableNpc\020=\022\031\n\025SkillSettle"
    "_CreateNpc\020>\022\013\n\007HomePet\020@\022\013\n\007PutSeat\020A\022\027"
    "\n\023ContinousCatchBonus\020B\022\014\n\010Activity\020C\022\r\n"
    "\tAIRefresh\020D\022\n\n\006Season\020E\022\025\n\021TravelingMer"
    "chant\020F\022\021\n\rHomePetLayEgg\020G\"{\n\027SpaceEnum_"
    "ActorMoveMode\"`\n\004ENUM\022\010\n\004None\020\000\022\013\n\007Walki"
    "ng\020\001\022\016\n\nNavWalking\020\002\022\013\n\007Falling\020\003\022\014\n\010Swi"
    "mming\020\004\022\n\n\006Flying\020\005\022\n\n\006Custom\020\006\"`\n\031Space"
    "Enum_NpcActionStatus\"C\n\004ENUM\022\016\n\nNotExecu"
    "te\020\000\022\r\n\tExecuting\020\001\022\016\n\nCommitable\020\002\022\014\n\010C"
    "ommited\020\003"
};
static ::absl::once_flag descriptor_table_space_5fenum_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_space_5fenum_2eproto = {
    false,
    false,
    1809,
    descriptor_table_protodef_space_5fenum_2eproto,
    "space_enum.proto",
    &descriptor_table_space_5fenum_2eproto_once,
    nullptr,
    0,
    7,
    schemas,
    file_message_globals,
    TableStruct_space_5fenum_2eproto::offsets,
    file_level_enum_descriptors_space_5fenum_2eproto,
    file_level_service_descriptors_space_5fenum_2eproto,
};
namespace Next {
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
SpaceEnum_SpaceObjType_ENUM_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_space_5fenum_2eproto);
  return file_level_enum_descriptors_space_5fenum_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t SpaceEnum_SpaceObjType_ENUM_internal_data_[] = {
    262145u, 0u, };
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
SpaceEnum_SpaceObjSubType_ENUM_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_space_5fenum_2eproto);
  return file_level_enum_descriptors_space_5fenum_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t SpaceEnum_SpaceObjSubType_ENUM_internal_data_[] = {
    131073u, 32u, 242u, };
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
SpaceEnum_ActorDetailType_ENUM_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_space_5fenum_2eproto);
  return file_level_enum_descriptors_space_5fenum_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t SpaceEnum_ActorDetailType_ENUM_internal_data_[] = {
    983041u, 0u, };
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
SpaceEnum_AvatarSceneChangeReason_ENUM_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_space_5fenum_2eproto);
  return file_level_enum_descriptors_space_5fenum_2eproto[3];
}
PROTOBUF_CONSTINIT const uint32_t SpaceEnum_AvatarSceneChangeReason_ENUM_internal_data_[] = {
    196609u, 0u, };
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
SpaceEnum_NpcRefreshSource_ENUM_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_space_5fenum_2eproto);
  return file_level_enum_descriptors_space_5fenum_2eproto[4];
}
PROTOBUF_CONSTINIT const uint32_t SpaceEnum_NpcRefreshSource_ENUM_internal_data_[] = {
    589824u, 64u, 14809084u, 2142243847u, };
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
SpaceEnum_ActorMoveMode_ENUM_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_space_5fenum_2eproto);
  return file_level_enum_descriptors_space_5fenum_2eproto[5];
}
PROTOBUF_CONSTINIT const uint32_t SpaceEnum_ActorMoveMode_ENUM_internal_data_[] = {
    458752u, 0u, };
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
SpaceEnum_NpcActionStatus_ENUM_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_space_5fenum_2eproto);
  return file_level_enum_descriptors_space_5fenum_2eproto[6];
}
PROTOBUF_CONSTINIT const uint32_t SpaceEnum_NpcActionStatus_ENUM_internal_data_[] = {
    262144u, 0u, };
// ===================================================================

SpaceEnum_SpaceObjType::SpaceEnum_SpaceObjType(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SpaceEnum_SpaceObjType_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:Next.SpaceEnum_SpaceObjType)
}
SpaceEnum_SpaceObjType::SpaceEnum_SpaceObjType(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SpaceEnum_SpaceObjType& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SpaceEnum_SpaceObjType_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SpaceEnum_SpaceObjType* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Next.SpaceEnum_SpaceObjType)
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SpaceEnum_SpaceObjType_class_data_ =
        SpaceEnum_SpaceObjType::InternalGenerateClassData_(SpaceEnum_SpaceObjType_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SpaceEnum_SpaceObjType::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SpaceEnum_SpaceObjType_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SpaceEnum_SpaceObjType_class_data_.tc_table);
  return SpaceEnum_SpaceObjType_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SpaceEnum_SpaceObjType::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SpaceEnum_SpaceObjType_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&SpaceEnum_SpaceObjType_globals_));
  return SpaceEnum_SpaceObjType_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const SpaceEnum_SpaceObjType::ParseTableT_
    SpaceEnum_SpaceObjType::_table_ =
        SpaceEnum_SpaceObjType::InternalGenerateParseTable_(SpaceEnum_SpaceObjType_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS







::google::protobuf::Metadata SpaceEnum_SpaceObjType::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

SpaceEnum_SpaceObjSubType::SpaceEnum_SpaceObjSubType(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SpaceEnum_SpaceObjSubType_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:Next.SpaceEnum_SpaceObjSubType)
}
SpaceEnum_SpaceObjSubType::SpaceEnum_SpaceObjSubType(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SpaceEnum_SpaceObjSubType& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SpaceEnum_SpaceObjSubType_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SpaceEnum_SpaceObjSubType* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Next.SpaceEnum_SpaceObjSubType)
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SpaceEnum_SpaceObjSubType_class_data_ =
        SpaceEnum_SpaceObjSubType::InternalGenerateClassData_(SpaceEnum_SpaceObjSubType_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SpaceEnum_SpaceObjSubType::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SpaceEnum_SpaceObjSubType_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SpaceEnum_SpaceObjSubType_class_data_.tc_table);
  return SpaceEnum_SpaceObjSubType_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SpaceEnum_SpaceObjSubType::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SpaceEnum_SpaceObjSubType_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&SpaceEnum_SpaceObjSubType_globals_));
  return SpaceEnum_SpaceObjSubType_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const SpaceEnum_SpaceObjSubType::ParseTableT_
    SpaceEnum_SpaceObjSubType::_table_ =
        SpaceEnum_SpaceObjSubType::InternalGenerateParseTable_(SpaceEnum_SpaceObjSubType_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS







::google::protobuf::Metadata SpaceEnum_SpaceObjSubType::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

SpaceEnum_ActorDetailType::SpaceEnum_ActorDetailType(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SpaceEnum_ActorDetailType_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:Next.SpaceEnum_ActorDetailType)
}
SpaceEnum_ActorDetailType::SpaceEnum_ActorDetailType(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SpaceEnum_ActorDetailType& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SpaceEnum_ActorDetailType_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SpaceEnum_ActorDetailType* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Next.SpaceEnum_ActorDetailType)
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SpaceEnum_ActorDetailType_class_data_ =
        SpaceEnum_ActorDetailType::InternalGenerateClassData_(SpaceEnum_ActorDetailType_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SpaceEnum_ActorDetailType::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SpaceEnum_ActorDetailType_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SpaceEnum_ActorDetailType_class_data_.tc_table);
  return SpaceEnum_ActorDetailType_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SpaceEnum_ActorDetailType::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SpaceEnum_ActorDetailType_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&SpaceEnum_ActorDetailType_globals_));
  return SpaceEnum_ActorDetailType_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const SpaceEnum_ActorDetailType::ParseTableT_
    SpaceEnum_ActorDetailType::_table_ =
        SpaceEnum_ActorDetailType::InternalGenerateParseTable_(SpaceEnum_ActorDetailType_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS







::google::protobuf::Metadata SpaceEnum_ActorDetailType::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

SpaceEnum_AvatarSceneChangeReason::SpaceEnum_AvatarSceneChangeReason(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SpaceEnum_AvatarSceneChangeReason_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:Next.SpaceEnum_AvatarSceneChangeReason)
}
SpaceEnum_AvatarSceneChangeReason::SpaceEnum_AvatarSceneChangeReason(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SpaceEnum_AvatarSceneChangeReason& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SpaceEnum_AvatarSceneChangeReason_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SpaceEnum_AvatarSceneChangeReason* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Next.SpaceEnum_AvatarSceneChangeReason)
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SpaceEnum_AvatarSceneChangeReason_class_data_ =
        SpaceEnum_AvatarSceneChangeReason::InternalGenerateClassData_(SpaceEnum_AvatarSceneChangeReason_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SpaceEnum_AvatarSceneChangeReason::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SpaceEnum_AvatarSceneChangeReason_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SpaceEnum_AvatarSceneChangeReason_class_data_.tc_table);
  return SpaceEnum_AvatarSceneChangeReason_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SpaceEnum_AvatarSceneChangeReason::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SpaceEnum_AvatarSceneChangeReason_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&SpaceEnum_AvatarSceneChangeReason_globals_));
  return SpaceEnum_AvatarSceneChangeReason_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const SpaceEnum_AvatarSceneChangeReason::ParseTableT_
    SpaceEnum_AvatarSceneChangeReason::_table_ =
        SpaceEnum_AvatarSceneChangeReason::InternalGenerateParseTable_(SpaceEnum_AvatarSceneChangeReason_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS







::google::protobuf::Metadata SpaceEnum_AvatarSceneChangeReason::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

SpaceEnum_NpcRefreshSource::SpaceEnum_NpcRefreshSource(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SpaceEnum_NpcRefreshSource_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:Next.SpaceEnum_NpcRefreshSource)
}
SpaceEnum_NpcRefreshSource::SpaceEnum_NpcRefreshSource(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SpaceEnum_NpcRefreshSource& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SpaceEnum_NpcRefreshSource_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SpaceEnum_NpcRefreshSource* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Next.SpaceEnum_NpcRefreshSource)
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SpaceEnum_NpcRefreshSource_class_data_ =
        SpaceEnum_NpcRefreshSource::InternalGenerateClassData_(SpaceEnum_NpcRefreshSource_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SpaceEnum_NpcRefreshSource::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SpaceEnum_NpcRefreshSource_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SpaceEnum_NpcRefreshSource_class_data_.tc_table);
  return SpaceEnum_NpcRefreshSource_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SpaceEnum_NpcRefreshSource::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SpaceEnum_NpcRefreshSource_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&SpaceEnum_NpcRefreshSource_globals_));
  return SpaceEnum_NpcRefreshSource_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const SpaceEnum_NpcRefreshSource::ParseTableT_
    SpaceEnum_NpcRefreshSource::_table_ =
        SpaceEnum_NpcRefreshSource::InternalGenerateParseTable_(SpaceEnum_NpcRefreshSource_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS







::google::protobuf::Metadata SpaceEnum_NpcRefreshSource::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

SpaceEnum_ActorMoveMode::SpaceEnum_ActorMoveMode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SpaceEnum_ActorMoveMode_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:Next.SpaceEnum_ActorMoveMode)
}
SpaceEnum_ActorMoveMode::SpaceEnum_ActorMoveMode(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SpaceEnum_ActorMoveMode& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SpaceEnum_ActorMoveMode_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SpaceEnum_ActorMoveMode* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Next.SpaceEnum_ActorMoveMode)
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SpaceEnum_ActorMoveMode_class_data_ =
        SpaceEnum_ActorMoveMode::InternalGenerateClassData_(SpaceEnum_ActorMoveMode_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SpaceEnum_ActorMoveMode::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SpaceEnum_ActorMoveMode_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SpaceEnum_ActorMoveMode_class_data_.tc_table);
  return SpaceEnum_ActorMoveMode_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SpaceEnum_ActorMoveMode::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SpaceEnum_ActorMoveMode_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&SpaceEnum_ActorMoveMode_globals_));
  return SpaceEnum_ActorMoveMode_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const SpaceEnum_ActorMoveMode::ParseTableT_
    SpaceEnum_ActorMoveMode::_table_ =
        SpaceEnum_ActorMoveMode::InternalGenerateParseTable_(SpaceEnum_ActorMoveMode_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS







::google::protobuf::Metadata SpaceEnum_ActorMoveMode::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

SpaceEnum_NpcActionStatus::SpaceEnum_NpcActionStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SpaceEnum_NpcActionStatus_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:Next.SpaceEnum_NpcActionStatus)
}
SpaceEnum_NpcActionStatus::SpaceEnum_NpcActionStatus(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SpaceEnum_NpcActionStatus& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SpaceEnum_NpcActionStatus_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SpaceEnum_NpcActionStatus* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Next.SpaceEnum_NpcActionStatus)
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SpaceEnum_NpcActionStatus_class_data_ =
        SpaceEnum_NpcActionStatus::InternalGenerateClassData_(SpaceEnum_NpcActionStatus_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SpaceEnum_NpcActionStatus::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SpaceEnum_NpcActionStatus_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SpaceEnum_NpcActionStatus_class_data_.tc_table);
  return SpaceEnum_NpcActionStatus_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SpaceEnum_NpcActionStatus::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SpaceEnum_NpcActionStatus_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&SpaceEnum_NpcActionStatus_globals_));
  return SpaceEnum_NpcActionStatus_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const SpaceEnum_NpcActionStatus::ParseTableT_
    SpaceEnum_NpcActionStatus::_table_ =
        SpaceEnum_NpcActionStatus::InternalGenerateParseTable_(SpaceEnum_NpcActionStatus_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS







::google::protobuf::Metadata SpaceEnum_NpcActionStatus::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Next
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_space_5fenum_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
