// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: story_flag.proto
// Protobuf C++ Version: 6.33.4

#include "story_flag.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Next {

inline constexpr ZonePlayerStoryFlagChangeNotify::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        change_type_{0},
        change_val_{0},
        version_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ZonePlayerStoryFlagChangeNotify::ZonePlayerStoryFlagChangeNotify(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ZonePlayerStoryFlagChangeNotify_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ZonePlayerStoryFlagChangeNotifyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ZonePlayerStoryFlagChangeNotifyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ZonePlayerStoryFlagChangeNotifyDefaultTypeInternal() {}
  union {
    ZonePlayerStoryFlagChangeNotify _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ZonePlayerStoryFlagChangeNotifyDefaultTypeInternal _ZonePlayerStoryFlagChangeNotify_default_instance_;

inline constexpr ZonePlayerMultiStoryFlagChangeNotify::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        change_val_{},
        change_type_{0},
        version_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ZonePlayerMultiStoryFlagChangeNotify::ZonePlayerMultiStoryFlagChangeNotify(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ZonePlayerMultiStoryFlagChangeNotify_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ZonePlayerMultiStoryFlagChangeNotifyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ZonePlayerMultiStoryFlagChangeNotifyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ZonePlayerMultiStoryFlagChangeNotifyDefaultTypeInternal() {}
  union {
    ZonePlayerMultiStoryFlagChangeNotify _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ZonePlayerMultiStoryFlagChangeNotifyDefaultTypeInternal _ZonePlayerMultiStoryFlagChangeNotify_default_instance_;
}  // namespace Next
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_story_5fflag_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_story_5fflag_2eproto = nullptr;
const ::uint32_t
    TableStruct_story_5fflag_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Next::ZonePlayerStoryFlagChangeNotify, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Next::ZonePlayerStoryFlagChangeNotify, _impl_.change_type_),
        PROTOBUF_FIELD_OFFSET(::Next::ZonePlayerStoryFlagChangeNotify, _impl_.change_val_),
        PROTOBUF_FIELD_OFFSET(::Next::ZonePlayerStoryFlagChangeNotify, _impl_.version_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Next::ZonePlayerMultiStoryFlagChangeNotify, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Next::ZonePlayerMultiStoryFlagChangeNotify, _impl_.change_type_),
        PROTOBUF_FIELD_OFFSET(::Next::ZonePlayerMultiStoryFlagChangeNotify, _impl_.change_val_),
        PROTOBUF_FIELD_OFFSET(::Next::ZonePlayerMultiStoryFlagChangeNotify, _impl_.version_),
        1,
        0,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Next::ZonePlayerStoryFlagChangeNotify)},
        {9, sizeof(::Next::ZonePlayerMultiStoryFlagChangeNotify)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::Next::_ZonePlayerStoryFlagChangeNotify_default_instance_._instance,
    &::Next::_ZonePlayerMultiStoryFlagChangeNotify_default_instance_._instance,
};
const char descriptor_table_protodef_story_5fflag_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020story_flag.proto\022\004Next\"[\n\037ZonePlayerSt"
    "oryFlagChangeNotify\022\023\n\013change_type\030\001 \001(\005"
    "\022\022\n\nchange_val\030\002 \001(\005\022\017\n\007version\030\003 \001(\005\"`\n"
    "$ZonePlayerMultiStoryFlagChangeNotify\022\023\n"
    "\013change_type\030\001 \001(\005\022\022\n\nchange_val\030\002 \003(\005\022\017"
    "\n\007version\030\003 \001(\005"
};
static ::absl::once_flag descriptor_table_story_5fflag_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_story_5fflag_2eproto = {
    false,
    false,
    215,
    descriptor_table_protodef_story_5fflag_2eproto,
    "story_flag.proto",
    &descriptor_table_story_5fflag_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_story_5fflag_2eproto::offsets,
    file_level_enum_descriptors_story_5fflag_2eproto,
    file_level_service_descriptors_story_5fflag_2eproto,
};
namespace Next {
// ===================================================================

class ZonePlayerStoryFlagChangeNotify::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ZonePlayerStoryFlagChangeNotify>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ZonePlayerStoryFlagChangeNotify, _impl_._has_bits_);
};

ZonePlayerStoryFlagChangeNotify::ZonePlayerStoryFlagChangeNotify(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ZonePlayerStoryFlagChangeNotify_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Next.ZonePlayerStoryFlagChangeNotify)
}
ZonePlayerStoryFlagChangeNotify::ZonePlayerStoryFlagChangeNotify(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ZonePlayerStoryFlagChangeNotify& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ZonePlayerStoryFlagChangeNotify_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE ZonePlayerStoryFlagChangeNotify::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void ZonePlayerStoryFlagChangeNotify::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, change_type_),
           0,
           offsetof(Impl_, version_) -
               offsetof(Impl_, change_type_) +
               sizeof(Impl_::version_));
}
ZonePlayerStoryFlagChangeNotify::~ZonePlayerStoryFlagChangeNotify() {
  // @@protoc_insertion_point(destructor:Next.ZonePlayerStoryFlagChangeNotify)
  SharedDtor(*this);
}
inline void ZonePlayerStoryFlagChangeNotify::SharedDtor(MessageLite& self) {
  ZonePlayerStoryFlagChangeNotify& this_ = static_cast<ZonePlayerStoryFlagChangeNotify&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ZonePlayerStoryFlagChangeNotify::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ZonePlayerStoryFlagChangeNotify(arena);
}
constexpr auto ZonePlayerStoryFlagChangeNotify::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ZonePlayerStoryFlagChangeNotify),
                                            alignof(ZonePlayerStoryFlagChangeNotify));
}
constexpr auto ZonePlayerStoryFlagChangeNotify::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ZonePlayerStoryFlagChangeNotify_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ZonePlayerStoryFlagChangeNotify::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ZonePlayerStoryFlagChangeNotify>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ZonePlayerStoryFlagChangeNotify::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ZonePlayerStoryFlagChangeNotify>(), &ZonePlayerStoryFlagChangeNotify::ByteSizeLong,
              &ZonePlayerStoryFlagChangeNotify::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ZonePlayerStoryFlagChangeNotify, _impl_._cached_size_),
          false,
      },
      &ZonePlayerStoryFlagChangeNotify::kDescriptorMethods,
      &descriptor_table_story_5fflag_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ZonePlayerStoryFlagChangeNotify_class_data_ =
        ZonePlayerStoryFlagChangeNotify::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ZonePlayerStoryFlagChangeNotify::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ZonePlayerStoryFlagChangeNotify_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ZonePlayerStoryFlagChangeNotify_class_data_.tc_table);
  return ZonePlayerStoryFlagChangeNotify_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
ZonePlayerStoryFlagChangeNotify::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ZonePlayerStoryFlagChangeNotify, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ZonePlayerStoryFlagChangeNotify_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Next::ZonePlayerStoryFlagChangeNotify>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 change_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ZonePlayerStoryFlagChangeNotify, _impl_.change_type_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(ZonePlayerStoryFlagChangeNotify, _impl_.change_type_)}},
    // optional int32 change_val = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ZonePlayerStoryFlagChangeNotify, _impl_.change_val_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(ZonePlayerStoryFlagChangeNotify, _impl_.change_val_)}},
    // optional int32 version = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ZonePlayerStoryFlagChangeNotify, _impl_.version_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(ZonePlayerStoryFlagChangeNotify, _impl_.version_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 change_type = 1;
    {PROTOBUF_FIELD_OFFSET(ZonePlayerStoryFlagChangeNotify, _impl_.change_type_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 change_val = 2;
    {PROTOBUF_FIELD_OFFSET(ZonePlayerStoryFlagChangeNotify, _impl_.change_val_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 version = 3;
    {PROTOBUF_FIELD_OFFSET(ZonePlayerStoryFlagChangeNotify, _impl_.version_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void ZonePlayerStoryFlagChangeNotify::Clear() {
// @@protoc_insertion_point(message_clear_start:Next.ZonePlayerStoryFlagChangeNotify)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    ::memset(&_impl_.change_type_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.version_) -
        reinterpret_cast<char*>(&_impl_.change_type_)) + sizeof(_impl_.version_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ZonePlayerStoryFlagChangeNotify::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ZonePlayerStoryFlagChangeNotify& this_ = static_cast<const ZonePlayerStoryFlagChangeNotify&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ZonePlayerStoryFlagChangeNotify::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ZonePlayerStoryFlagChangeNotify& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Next.ZonePlayerStoryFlagChangeNotify)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int32 change_type = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_change_type(), target);
  }

  // optional int32 change_val = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
            stream, this_._internal_change_val(), target);
  }

  // optional int32 version = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
            stream, this_._internal_version(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Next.ZonePlayerStoryFlagChangeNotify)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ZonePlayerStoryFlagChangeNotify::ByteSizeLong(const MessageLite& base) {
  const ZonePlayerStoryFlagChangeNotify& this_ = static_cast<const ZonePlayerStoryFlagChangeNotify&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ZonePlayerStoryFlagChangeNotify::ByteSizeLong() const {
  const ZonePlayerStoryFlagChangeNotify& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Next.ZonePlayerStoryFlagChangeNotify)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // optional int32 change_type = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_change_type());
    }
    // optional int32 change_val = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_change_val());
    }
    // optional int32 version = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_version());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ZonePlayerStoryFlagChangeNotify::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ZonePlayerStoryFlagChangeNotify*>(&to_msg);
  auto& from = static_cast<const ZonePlayerStoryFlagChangeNotify&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Next.ZonePlayerStoryFlagChangeNotify)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.change_type_ = from._impl_.change_type_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.change_val_ = from._impl_.change_val_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.version_ = from._impl_.version_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ZonePlayerStoryFlagChangeNotify::CopyFrom(const ZonePlayerStoryFlagChangeNotify& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Next.ZonePlayerStoryFlagChangeNotify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ZonePlayerStoryFlagChangeNotify::InternalSwap(ZonePlayerStoryFlagChangeNotify* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ZonePlayerStoryFlagChangeNotify, _impl_.version_)
      + sizeof(ZonePlayerStoryFlagChangeNotify::_impl_.version_)
      - PROTOBUF_FIELD_OFFSET(ZonePlayerStoryFlagChangeNotify, _impl_.change_type_)>(
          reinterpret_cast<char*>(&_impl_.change_type_),
          reinterpret_cast<char*>(&other->_impl_.change_type_));
}

::google::protobuf::Metadata ZonePlayerStoryFlagChangeNotify::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ZonePlayerMultiStoryFlagChangeNotify::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ZonePlayerMultiStoryFlagChangeNotify>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ZonePlayerMultiStoryFlagChangeNotify, _impl_._has_bits_);
};

ZonePlayerMultiStoryFlagChangeNotify::ZonePlayerMultiStoryFlagChangeNotify(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ZonePlayerMultiStoryFlagChangeNotify_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Next.ZonePlayerMultiStoryFlagChangeNotify)
}
PROTOBUF_NDEBUG_INLINE ZonePlayerMultiStoryFlagChangeNotify::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Next::ZonePlayerMultiStoryFlagChangeNotify& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        change_val_{visibility, arena, from.change_val_} {}

ZonePlayerMultiStoryFlagChangeNotify::ZonePlayerMultiStoryFlagChangeNotify(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ZonePlayerMultiStoryFlagChangeNotify& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ZonePlayerMultiStoryFlagChangeNotify_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ZonePlayerMultiStoryFlagChangeNotify* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, change_type_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, change_type_),
           offsetof(Impl_, version_) -
               offsetof(Impl_, change_type_) +
               sizeof(Impl_::version_));

  // @@protoc_insertion_point(copy_constructor:Next.ZonePlayerMultiStoryFlagChangeNotify)
}
PROTOBUF_NDEBUG_INLINE ZonePlayerMultiStoryFlagChangeNotify::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        change_val_{visibility, arena} {}

inline void ZonePlayerMultiStoryFlagChangeNotify::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, change_type_),
           0,
           offsetof(Impl_, version_) -
               offsetof(Impl_, change_type_) +
               sizeof(Impl_::version_));
}
ZonePlayerMultiStoryFlagChangeNotify::~ZonePlayerMultiStoryFlagChangeNotify() {
  // @@protoc_insertion_point(destructor:Next.ZonePlayerMultiStoryFlagChangeNotify)
  SharedDtor(*this);
}
inline void ZonePlayerMultiStoryFlagChangeNotify::SharedDtor(MessageLite& self) {
  ZonePlayerMultiStoryFlagChangeNotify& this_ = static_cast<ZonePlayerMultiStoryFlagChangeNotify&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ZonePlayerMultiStoryFlagChangeNotify::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ZonePlayerMultiStoryFlagChangeNotify(arena);
}
constexpr auto ZonePlayerMultiStoryFlagChangeNotify::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ZonePlayerMultiStoryFlagChangeNotify, _impl_.change_val_) +
          decltype(ZonePlayerMultiStoryFlagChangeNotify::_impl_.change_val_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ZonePlayerMultiStoryFlagChangeNotify), alignof(ZonePlayerMultiStoryFlagChangeNotify), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ZonePlayerMultiStoryFlagChangeNotify::PlacementNew_,
                                 sizeof(ZonePlayerMultiStoryFlagChangeNotify),
                                 alignof(ZonePlayerMultiStoryFlagChangeNotify));
  }
}
constexpr auto ZonePlayerMultiStoryFlagChangeNotify::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ZonePlayerMultiStoryFlagChangeNotify_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ZonePlayerMultiStoryFlagChangeNotify::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ZonePlayerMultiStoryFlagChangeNotify>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ZonePlayerMultiStoryFlagChangeNotify::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ZonePlayerMultiStoryFlagChangeNotify>(), &ZonePlayerMultiStoryFlagChangeNotify::ByteSizeLong,
              &ZonePlayerMultiStoryFlagChangeNotify::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ZonePlayerMultiStoryFlagChangeNotify, _impl_._cached_size_),
          false,
      },
      &ZonePlayerMultiStoryFlagChangeNotify::kDescriptorMethods,
      &descriptor_table_story_5fflag_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ZonePlayerMultiStoryFlagChangeNotify_class_data_ =
        ZonePlayerMultiStoryFlagChangeNotify::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ZonePlayerMultiStoryFlagChangeNotify::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ZonePlayerMultiStoryFlagChangeNotify_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ZonePlayerMultiStoryFlagChangeNotify_class_data_.tc_table);
  return ZonePlayerMultiStoryFlagChangeNotify_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
ZonePlayerMultiStoryFlagChangeNotify::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ZonePlayerMultiStoryFlagChangeNotify, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ZonePlayerMultiStoryFlagChangeNotify_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Next::ZonePlayerMultiStoryFlagChangeNotify>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 change_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ZonePlayerMultiStoryFlagChangeNotify, _impl_.change_type_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(ZonePlayerMultiStoryFlagChangeNotify, _impl_.change_type_)}},
    // repeated int32 change_val = 2;
    {::_pbi::TcParser::FastV32R1,
     {16, 0, 0,
      PROTOBUF_FIELD_OFFSET(ZonePlayerMultiStoryFlagChangeNotify, _impl_.change_val_)}},
    // optional int32 version = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ZonePlayerMultiStoryFlagChangeNotify, _impl_.version_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(ZonePlayerMultiStoryFlagChangeNotify, _impl_.version_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 change_type = 1;
    {PROTOBUF_FIELD_OFFSET(ZonePlayerMultiStoryFlagChangeNotify, _impl_.change_type_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // repeated int32 change_val = 2;
    {PROTOBUF_FIELD_OFFSET(ZonePlayerMultiStoryFlagChangeNotify, _impl_.change_val_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kInt32)},
    // optional int32 version = 3;
    {PROTOBUF_FIELD_OFFSET(ZonePlayerMultiStoryFlagChangeNotify, _impl_.version_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void ZonePlayerMultiStoryFlagChangeNotify::Clear() {
// @@protoc_insertion_point(message_clear_start:Next.ZonePlayerMultiStoryFlagChangeNotify)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.change_val_.Clear();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000006U)) {
    ::memset(&_impl_.change_type_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.version_) -
        reinterpret_cast<char*>(&_impl_.change_type_)) + sizeof(_impl_.version_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ZonePlayerMultiStoryFlagChangeNotify::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ZonePlayerMultiStoryFlagChangeNotify& this_ = static_cast<const ZonePlayerMultiStoryFlagChangeNotify&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ZonePlayerMultiStoryFlagChangeNotify::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ZonePlayerMultiStoryFlagChangeNotify& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Next.ZonePlayerMultiStoryFlagChangeNotify)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int32 change_type = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_change_type(), target);
  }

  // repeated int32 change_val = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_change_val_size(); i < n; ++i) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteInt32ToArray(
          2, this_._internal_change_val().Get(i), target);
    }
  }

  // optional int32 version = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
            stream, this_._internal_version(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Next.ZonePlayerMultiStoryFlagChangeNotify)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ZonePlayerMultiStoryFlagChangeNotify::ByteSizeLong(const MessageLite& base) {
  const ZonePlayerMultiStoryFlagChangeNotify& this_ = static_cast<const ZonePlayerMultiStoryFlagChangeNotify&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ZonePlayerMultiStoryFlagChangeNotify::ByteSizeLong() const {
  const ZonePlayerMultiStoryFlagChangeNotify& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Next.ZonePlayerMultiStoryFlagChangeNotify)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // repeated int32 change_val = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      ::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
          this_._internal_change_val());
      ::size_t tag_size = ::size_t{1} *
          ::_pbi::FromIntSize(this_._internal_change_val_size());
      total_size += tag_size + data_size;
    }
    // optional int32 change_type = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_change_type());
    }
    // optional int32 version = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_version());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ZonePlayerMultiStoryFlagChangeNotify::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ZonePlayerMultiStoryFlagChangeNotify*>(&to_msg);
  auto& from = static_cast<const ZonePlayerMultiStoryFlagChangeNotify&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Next.ZonePlayerMultiStoryFlagChangeNotify)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_change_val()->MergeFrom(from._internal_change_val());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.change_type_ = from._impl_.change_type_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.version_ = from._impl_.version_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ZonePlayerMultiStoryFlagChangeNotify::CopyFrom(const ZonePlayerMultiStoryFlagChangeNotify& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Next.ZonePlayerMultiStoryFlagChangeNotify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ZonePlayerMultiStoryFlagChangeNotify::InternalSwap(ZonePlayerMultiStoryFlagChangeNotify* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.change_val_.InternalSwap(&other->_impl_.change_val_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ZonePlayerMultiStoryFlagChangeNotify, _impl_.version_)
      + sizeof(ZonePlayerMultiStoryFlagChangeNotify::_impl_.version_)
      - PROTOBUF_FIELD_OFFSET(ZonePlayerMultiStoryFlagChangeNotify, _impl_.change_type_)>(
          reinterpret_cast<char*>(&_impl_.change_type_),
          reinterpret_cast<char*>(&other->_impl_.change_type_));
}

::google::protobuf::Metadata ZonePlayerMultiStoryFlagChangeNotify::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Next
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_story_5fflag_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
