#!/usr/bin/env python3
"""Generate C++ ZoneOpcode enum and lookup helpers from proto.json."""

from __future__ import annotations

import json
import sys
from pathlib import Path


def message_short_name(full_name: str) -> str:
    name = full_name.strip()
    if name.startswith("."):
        name = name[1:]
    return name.rsplit(".", 1)[-1]


def render_header(entries: list[tuple[int, str, str]]) -> str:
    lines = [
        "// Auto-generated by scripts/generate_zone_opcodes.py. Do not edit.",
        "#pragma once",
        "",
        "#include <QtGlobal>",
        "",
        "#include <QSet>",
        "",
        "namespace rwtd {",
        "",
        "enum class ZoneOpcode : quint32 {",
        "    Unknown = 0,",
    ]
    for opcode, short_name, _full_name in entries:
        lines.append(f"    {short_name} = {opcode},")
    lines.extend(
        [
            "};",
            "",
            "inline ZoneOpcode zoneOpcodeFromRaw(quint32 opcode)",
            "{",
            "    return static_cast<ZoneOpcode>(opcode);",
            "}",
            "",
            "bool isKnownZoneOpcode(quint32 opcode);",
            "const QSet<quint32> &knownZoneOpcodes();",
            "",
            "} // namespace rwtd",
            "",
        ]
    )
    return "\n".join(lines)


def render_source(entries: list[tuple[int, str, str]]) -> str:
    opcode_literals = ", ".join(str(opcode) for opcode, _, _ in entries)
    return "\n".join(
        [
            "// Auto-generated by scripts/generate_zone_opcodes.py. Do not edit.",
            "",
            '#include "rwtd/zone_opcodes.h"',
            "",
            "#include <QSet>",
            "",
            "namespace rwtd {",
            "namespace {",
            "",
            "const QSet<quint32> &opcodeSet()",
            "{",
            f"    static const QSet<quint32> opcodes = {{{opcode_literals}}};",
            "    return opcodes;",
            "}",
            "",
            "} // namespace",
            "",
            "bool isKnownZoneOpcode(quint32 opcode)",
            "{",
            "    return opcodeSet().contains(opcode);",
            "}",
            "",
            "const QSet<quint32> &knownZoneOpcodes()",
            "{",
            "    return opcodeSet();",
            "}",
            "",
            "} // namespace rwtd",
            "",
        ]
    )


def main() -> int:
    if len(sys.argv) != 4:
        print(f"usage: {sys.argv[0]} <proto.json> <output.h> <output.cpp>", file=sys.stderr)
        return 1

    proto_path = Path(sys.argv[1])
    header_path = Path(sys.argv[2])
    source_path = Path(sys.argv[3])

    data = json.loads(proto_path.read_text(encoding="utf-8"))
    entries: list[tuple[int, str, str]] = []
    for raw_opcode, full_name in data.items():
        if not isinstance(full_name, str):
            continue
        opcode = int(raw_opcode)
        short_name = message_short_name(full_name)
        entries.append((opcode, short_name, full_name))

    entries.sort(key=lambda item: item[0])
    header_path.parent.mkdir(parents=True, exist_ok=True)
    source_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(render_header(entries), encoding="utf-8")
    source_path.write_text(render_source(entries), encoding="utf-8")
    print(f"generated {header_path} and {source_path} ({len(entries)} opcodes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
