#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import secrets
import shlex
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BITS = 4096
PUBLIC_EXPONENT = 65537
URL_XOR_KEY = 0x5A
MODULUS_XOR_KEY = 0xA7
DEFAULT_URL_TEMPLATE = "https://h3110w0r1d.com/roco-helper-plugin/v{version}.php"
DEFAULT_REMOTE_HOST = "root@h3110w0r1d.com"
DEFAULT_REMOTE_DIR = "/root/web/www/blog/roco-helper-plugin"
VERSION_PATTERN = re.compile(r"^v?(?P<text>(?P<numeric>\d+(?:\.\d+){1,3})(?:[-+][A-Za-z0-9][A-Za-z0-9._-]*)?)$")
RUNTIME_STRINGS = {
    "disclaimer": [
        "本工具完全免费，请勿付费购买\nGitHub：https://github.com/h3110w0r1d-y/rocom-helper",
    ],
}


def is_probable_prime(value: int) -> bool:
    if value < 2:
        return False
    small_primes = [3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41]
    for prime in small_primes:
        if value % prime == 0:
            return value == prime

    d = value - 1
    s = 0
    while d % 2 == 0:
        s += 1
        d //= 2

    for witness in [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]:
        if witness >= value - 2:
            continue
        x = pow(witness, d, value)
        if x == 1 or x == value - 1:
            continue
        for _ in range(s - 1):
            x = pow(x, 2, value)
            if x == value - 1:
                break
        else:
            return False
    return True


def generate_prime(bits: int, exponent: int) -> int:
    while True:
        value = secrets.randbits(bits) | (1 << (bits - 1)) | 1
        if math.gcd(exponent, value - 1) != 1:
            continue
        if is_probable_prime(value):
            return value


def generate_keypair() -> tuple[int, int, int]:
    p = generate_prime(BITS // 2, PUBLIC_EXPONENT)
    while True:
        q = generate_prime(BITS // 2, PUBLIC_EXPONENT)
        if q != p:
            return p, q, p * q


def xor_bytes(data: bytes, key: int) -> bytes:
    return bytes(byte ^ key for byte in data)


def cpp_array(data: bytes, indent: str = "        ", width: int = 12) -> str:
    lines = []
    for index in range(0, len(data), width):
        chunk = data[index:index + width]
        lines.append(indent + ", ".join(f"0x{byte:02X}" for byte in chunk) + ",")
    return "\n".join(lines)


def runtime_key(seed: bytes, purpose: str) -> bytes:
    return hashlib.sha256(seed + purpose.encode("ascii")).digest()


def encode_runtime_text(seed: bytes, purpose: str, text: str) -> bytes:
    raw = text.encode("utf-8" if purpose == "disclaimer" else "ascii")
    key = runtime_key(seed, purpose)
    return bytes(byte ^ key[index % len(key)] for index, byte in enumerate(raw))


def php_single_quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def render_php(p: int, q: int, payload_json: str) -> str:
    return f"""<?php
declare(strict_types=1);

// Generated by scripts/release_crypto.py.
// RSA private operation + PKCS#1 v1.5 type 2 random padding.
// 插件 payload 只包含版本和运行时 seed，客户端连续 3 次校验失败会退出。

$RSA_E = '{PUBLIC_EXPONENT}';
$RSA_P_HEX = '{p:x}';
$RSA_Q_HEX = '{q:x}';
$PAYLOAD_JSON = '{php_single_quote(payload_json)}';

function require_gmp(): void
{{
    if (!extension_loaded('gmp')) {{
        throw new RuntimeException('PHP GMP extension is required.');
    }}
}}

function gmp_from_bytes(string $bytes)
{{
    $hex = bin2hex($bytes);
    return gmp_init($hex === '' ? '0' : $hex, 16);
}}

function gmp_to_bytes($value, int $size): string
{{
    $hex = gmp_strval($value, 16);
    if ((strlen($hex) % 2) !== 0) {{
        $hex = '0' . $hex;
    }}
    $bytes = hex2bin($hex);
    if ($bytes === false) {{
        $bytes = '';
    }}
    if (strlen($bytes) > $size) {{
        return substr($bytes, -$size);
    }}
    return str_pad($bytes, $size, "\\x00", STR_PAD_LEFT);
}}

function non_zero_random_bytes(int $length): string
{{
    $result = '';
    while (strlen($result) < $length) {{
        $chunk = random_bytes($length - strlen($result));
        $chunk = str_replace("\\x00", '', $chunk);
        $result .= $chunk;
    }}
    return $result;
}}

function rsa_private_encrypt_pkcs1_v15(string $payload, string $pHex, string $qHex, string $eText): string
{{
    require_gmp();
    $p = gmp_init($pHex, 16);
    $q = gmp_init($qHex, 16);
    $e = gmp_init($eText, 10);
    $n = gmp_mul($p, $q);
    $phi = gmp_mul(gmp_sub($p, 1), gmp_sub($q, 1));
    $d = gmp_invert($e, $phi);
    if ($d === false) {{
        throw new RuntimeException('Invalid RSA parameters: e has no inverse.');
    }}

    $modulusSize = intdiv(strlen(gmp_strval($n, 16)) + 1, 2);
    $maxPayloadSize = $modulusSize - 11;
    if (strlen($payload) > $maxPayloadSize) {{
        throw new RuntimeException("Payload too large, max bytes: {{$maxPayloadSize}}");
    }}

    $paddingSize = $modulusSize - strlen($payload) - 3;
    $encoded = "\\x00\\x02" . non_zero_random_bytes($paddingSize) . "\\x00" . $payload;
    return gmp_to_bytes(gmp_powm(gmp_from_bytes($encoded), $d, $n), $modulusSize);
}}

try {{
    header('Content-Type: text/plain; charset=utf-8');
    echo base64_encode(rsa_private_encrypt_pkcs1_v15($PAYLOAD_JSON, $RSA_P_HEX, $RSA_Q_HEX, $RSA_E));
}} catch (Throwable $e) {{
    http_response_code(500);
    echo '检查更新失败，软件退出';
}}
"""


def patch_file(path: Path, updated: str) -> bool:
    old = path.read_text(encoding="utf-8")
    if old == updated:
        return False
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(updated)
    print(f"updated {path.relative_to(ROOT)}")
    return True


def release_version_text(version: str) -> str:
    match = VERSION_PATTERN.fullmatch(version.strip())
    if match is None:
        raise RuntimeError("version must look like 2.0 or v2.0.1-beta1")
    return match.group("text")


def cmake_numeric_version(version: str) -> str:
    match = VERSION_PATTERN.fullmatch(version.strip())
    if match is None:
        raise RuntimeError("version must look like 2.0 or v2.0.1-beta1")
    return match.group("numeric")


def remote_filename(version: str) -> str:
    return f"v{release_version_text(version)}.php"


def remote_php_path(version: str, remote_dir: str) -> str:
    return f"{remote_dir.rstrip('/')}/{remote_filename(version)}"


def ssh_run(remote_host: str, command: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["ssh", remote_host, command],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )


def remote_file_exists(remote_host: str, remote_path: str) -> bool:
    result = ssh_run(remote_host, f"test -e {shlex.quote(remote_path)}")
    if result.returncode == 0:
        return True
    if result.returncode == 1:
        return False
    message = result.stderr.strip() or result.stdout.strip() or "unknown ssh error"
    raise RuntimeError(f"failed to check remote file: {message}")


def confirm_remote_overwrite(remote_host: str, remote_path: str) -> None:
    if not remote_file_exists(remote_host, remote_path):
        return
    answer = input(f"remote file exists: {remote_host}:{remote_path}\nForce update? [y/N] ").strip().lower()
    if answer not in {"y", "yes"}:
        raise RuntimeError("remote file already exists; aborting")


def upload_php(local_path: Path, remote_host: str, remote_dir: str, version: str) -> None:
    remote_path = remote_php_path(version, remote_dir)
    mkdir_result = ssh_run(remote_host, f"mkdir -p {shlex.quote(remote_dir)}")
    if mkdir_result.returncode != 0:
        message = mkdir_result.stderr.strip() or mkdir_result.stdout.strip() or "unknown ssh error"
        raise RuntimeError(f"failed to create remote directory: {message}")

    result = subprocess.run(
        ["scp", str(local_path), f"{remote_host}:{remote_path}"],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    if result.returncode != 0:
        message = result.stderr.strip() or result.stdout.strip() or "unknown scp error"
        raise RuntimeError(f"failed to upload PHP gate: {message}")
    print(f"uploaded {local_path.relative_to(ROOT)} -> {remote_host}:{remote_path}")


def replace_one(pattern: str, replacement: str, content: str, label: str) -> str:
    updated, count = re.subn(pattern, replacement, content, count=1, flags=re.S)
    if count != 1:
        raise RuntimeError(f"failed to patch {label}")
    return updated


def patch_main_cpp(version_url: str, n: int) -> None:
    path = ROOT / "src/main.cpp"
    content = path.read_text(encoding="utf-8")
    content = re.sub(
        r"constexpr uint32_t UpdateCheckRsaExponent = \d+;",
        f"constexpr uint32_t UpdateCheckRsaExponent = {PUBLIC_EXPONENT};",
        content,
        count=1,
    )
    url_body = f"""QString decodedUpdateCheckUrl()
{{
    static constexpr unsigned char key = 0x{URL_XOR_KEY:02x};
    static constexpr unsigned char data[] = {{
{cpp_array(xor_bytes(version_url.encode("ascii"), URL_XOR_KEY))}
    }};

    QByteArray url;
    url.reserve(static_cast<int>(std::size(data)));
    for (unsigned char ch : data) {{
        url.append(static_cast<char>(ch ^ key));
    }}
    return QString::fromLatin1(url);
}}
"""
    modulus_size = (n.bit_length() + 7) // 8
    modulus_body = f"""QByteArray decodedUpdateCheckModulus()
{{
    static constexpr unsigned char key = 0x{MODULUS_XOR_KEY:02x};
    static constexpr unsigned char data[] = {{
{cpp_array(xor_bytes(n.to_bytes(modulus_size, "big"), MODULUS_XOR_KEY))}
    }};

    QByteArray modulus;
    modulus.reserve(static_cast<int>(std::size(data)));
    for (unsigned char ch : data) {{
        modulus.append(static_cast<char>(ch ^ key));
    }}
    return modulus;
}}
"""
    content = replace_one(
        r"QString decodedUpdateCheckUrl\(\)\n\{.*?\n\}\n\nQByteArray decodedUpdateCheckModulus",
        url_body + "\nQByteArray decodedUpdateCheckModulus",
        content,
        "decodedUpdateCheckUrl",
    )
    content = replace_one(
        r"QByteArray decodedUpdateCheckModulus\(\)\n\{.*?\n\}\n\nQByteArray rsaPublicDecryptPkcs1V15",
        modulus_body + "\nQByteArray rsaPublicDecryptPkcs1V15",
        content,
        "decodedUpdateCheckModulus",
    )
    patch_file(path, content)


def patch_runtime_context_cpp(seed: bytes) -> None:
    path = ROOT / "src/data/runtime_context.cpp"
    content = path.read_text(encoding="utf-8")
    disclaimer = encode_runtime_text(seed, "disclaimer", RUNTIME_STRINGS["disclaimer"][0])
    disclaimer_fn = f"""QString RuntimeContext::startupDisclaimer() const
{{
    static constexpr unsigned char data[] = {{
{cpp_array(disclaimer)}
    }};
    if (!isValid()) {{
        return {{}};
    }}
    return decodeRuntimeTextUtf8(data, deriveKey(seed, "disclaimer"));
}}
"""
    content = replace_one(
        r"QString RuntimeContext::startupDisclaimer\(\) const\n\{.*?\n\}\n\nRuntimeContext makeRuntimeContext",
        disclaimer_fn + "\nRuntimeContext makeRuntimeContext",
        content,
        "startupDisclaimer",
    )
    patch_file(path, content)


def patch_cmake(version: str) -> None:
    path = ROOT / "CMakeLists.txt"
    content = path.read_text(encoding="utf-8")
    numeric = cmake_numeric_version(version)
    text = release_version_text(version)
    content = re.sub(
        r"project\(roco_helper_plugin VERSION [^ ]+ LANGUAGES CXX\)",
        f"project(roco_helper_plugin VERSION {numeric} LANGUAGES CXX)",
        content,
        count=1,
    )
    content = re.sub(
        r"set\(ROCO_APP_VERSION \"[^\"]+\"\)",
        f"set(ROCO_APP_VERSION \"{text}\")",
        content,
        count=1,
    )
    patch_file(path, content)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Rotate plugin release RSA keys, gate payload, URL, and app version.")
    parser.add_argument("--version", required=True, help="Release version, for example 2.0 or v2.0.1-beta1")
    parser.add_argument("--url", help="Update gate URL. Defaults to h3110w0r1d.com v{version}.php")
    parser.add_argument("--no-upload", action="store_true", help="Generate files locally without SSH/SCP upload")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    version = release_version_text(args.version)
    url = args.url or DEFAULT_URL_TEMPLATE.format(version=version)
    remote_path = remote_php_path(version, DEFAULT_REMOTE_DIR)
    if not args.no_upload:
        confirm_remote_overwrite(DEFAULT_REMOTE_HOST, remote_path)

    seed = secrets.token_bytes(32)
    payload = {"v": version, "s": seed.hex()}
    payload_json = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    if len(payload_json.encode("utf-8")) > 500:
        raise RuntimeError("gate payload JSON exceeds 500 bytes")

    print("generating 4096-bit RSA keypair...")
    p, q, n = generate_keypair()
    patch_cmake(version)
    patch_main_cpp(url, n)
    patch_runtime_context_cpp(seed)
    php_path = ROOT / "scripts/update_gate_response.php"
    patch_file(php_path, render_php(p, q, payload_json))
    if not args.no_upload:
        upload_php(php_path, DEFAULT_REMOTE_HOST, DEFAULT_REMOTE_DIR, version)
    print(f"payload_bytes={len(payload_json.encode('utf-8'))}")
    print(f"url={url}")
    print("done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
